---
title: "MR.ASH Results"
output:
  workflowr::wflow_html:
    code_folding: hide
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

The experiment is based on the following simulation setting.

```{r ridge}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(mr.ash.alpha); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
sa2          = (2^((0:19) / 20) - 1)^2
tdat1        = list()
tdat1[[1]]   = list()
n            = 1000
p            = 500
s_range      = c(1,2,5,10,20,50,100,200,500)
pred         = double(20)
time         = double(20)
sig          = double(20)
res_df       = readRDS("results/newridge10.RDS")
for (iter in 9:1) {
for (i in 1:20) {
  data          = simulate_data(n, p, s_range[iter], seed = i, signal = "normal", pve = 0.5)
  fit           = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                             sa2 = sa2)
  pred[i]       = fit$rsse / data$sigma / sqrt(n)
  time[i]       = fit$t
  sig[i]        = data$sigma
  cat("pred:",round(pred[i] / res_df[[iter]]$pred[i], digits = 3), ", time:", round(time[i] / res_df[[iter]]$time[i], digits = 3), "\n")
}
cat("---------------------\n")
tdat1[[1]][[iter]] = data.frame(pred = c(pred), time = c(time), p = p_range[iter],
                                sa2 = sa2, sigma = c(sig), name = "Ridge")
}
```

```{r nonconvex}
n            = 500
p            = 2000
s            = 20
tdat1[[2]]   = list()
signal_list  = c("lap","t2","t5","normal","unif","const")
res_df       = readRDS("results/signalshape_pve0.99.RDS")
for (iter in 1:6) {
for (i in 1:20) {
  data          = simulate_data(n, p, s = s, seed = i, signal = signal_list[iter], pve = 0.99)
  fit           = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                             sa2 = sa2)
  
  pred[i]       = fit$rsse / data$sigma / sqrt(n)
  time[i]       = fit$t
  sig[i]        = data$sigma
  cat(round(pred[i] / res_df[[iter]]$pred[i], digits = 3), " ")
}
cat("\n")
tdat1[[2]][[iter]] = data.frame(pred = c(pred), time = c(time), signal = signal_list[iter],
                                sa2 = sa2, sigma = c(sig), name = "Nonconvex")
}
```

```{r highdim}
n            = 500
p_range      = c(50,500,5000,50000)
s            = 20
tdat1[[3]]   = list()
res_df       = readRDS("results/highdim_pve0.5.RDS")
for (iter in 1:4) {
for (i in 1:20) {
  data          = simulate_data(n, p_range[iter], s = s, seed = i, signal = "normal", pve = 0.5)
  fit           = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                             sa2 = sa2)
  
  pred[i]       = fit$rsse / data$sigma / sqrt(n)
  time[i]       = fit$t
  sig[i]        = data$sigma
  cat(round(pred[i] / res_df[[iter]]$pred[i], digits = 3), " ")
}
cat("\n")
tdat1[[3]][[iter]] = data.frame(pred = c(pred), time = c(time), p = p_range[iter],
                                sa2 = sa2, sigma = c(sig), name = "Highdim")
}
```

```{r sparsity}
n            = 500
p            = 2000
s_range      = c(1,5,20,100,500,2000)
tdat1[[4]]   = list()
res_df       = readRDS("results/highdim_pve0.5.RDS")
for (iter in 1:5) {
for (i in 1:20) {
  data          = simulate_data(n, p, s = s_range[iter], seed = i, signal = "normal", pve = 0.5)
  fit           = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                             sa2 = sa2)
  
  pred[i]       = fit$rsse / data$sigma / sqrt(n)
  time[i]       = fit$t
  sig[i]        = data$sigma
  cat(round(pred[i] / res_df[[iter]]$pred[i], digits = 3), " ")
}
cat("\n")
tdat1[[4]][[iter]] = data.frame(pred = c(pred), time = c(time), s = s_range[iter],
                                sa2 = sa2, sigma = c(sig), name = "Sparsity")
}
```

```{r pve}
n            = 500
p            = 2000
s            = 20
pve_range    = seq(0,1,0.1)
tdat1[[5]]   = list()
res_df       = readRDS("results/diffpve.RDS")
for (iter in 1:11) {
for (i in 1:20) {
  data          = simulate_data(n, p, s = s, seed = i, signal = "normal", pve = pve_range[iter])
  fit           = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                             sa2 = sa2)
  
  if (data$sigma == 0) {
    data$sigma = 1
  }
  pred[i]       = fit$rsse / data$sigma / sqrt(n)
  time[i]       = fit$t
  sig[i]        = data$sigma
  cat(round(pred[i] / res_df[[iter]]$pred[i], digits = 3), " ")
}
cat("\n")
tdat1[[5]][[iter]] = data.frame(pred = c(pred), time = c(time), pve = pve_range[iter],
                                sa2 = sa2, sigma = c(sig), name = "PVE")
}
```

```{r lowdim}
n            = 1010
p            = 1000
s            = 20
res_df       = readRDS("results/subogdancandesnew.RDS")
for (i in 1:20) {
  set.seed(2010 + i)
  beta            = double(p)
  ind             = sample(p,s)
  M               = 5
  beta[ind]       = 1/M
  beta[ind[1:10]] = M
  data            = simulate_data(n, p, s = s, seed = i, beta = beta, sigma = 1)
  fit             = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                               sa2 = (2^((0:19) / 2) - 1)^2)
  
  pred[i]       = fit$rsse / data$sigma / sqrt(n)
  time[i]       = fit$t
  sig[i]        = data$sigma
  cat(round(pred[i] / res_df[[1]]$pred[i], digits = 3), " ")
}
cat("\n")
tdat1[[6]] = data.frame(pred = c(pred), time = c(time), beta = beta, pi = c(fit$fit$pi),
                        sa2 = sa2, sigma = c(sig), name = "lowdim")
```

```{r lowdim}
n            = 1010
p            = 1000
s            = 20
res_df       = readRDS("results/subogdancandesnew.RDS")
for (i in 1:20) {
  set.seed(2010 + i)
  beta            = double(p)
  ind             = sample(p,s)
  M               = 5
  beta[ind]       = 1/M
  beta[ind[1:10]] = M
  data            = simulate_data(n, p, s = s, seed = i, beta = beta, sigma = 1)
  fit             = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                               sa2 = (2^((0:19) / 2) - 1)^2)
  
  pred[i]       = fit$rsse / data$sigma / sqrt(n)
  time[i]       = fit$t
  sig[i]        = data$sigma
  cat(round(pred[i] / res_df[[1]]$pred[i], digits = 3), " ")
}
cat("\n")
tdat1[[6]] = data.frame(pred = c(pred), time = c(time), beta = beta, pi = c(fit$fit$pi),
                        sa2 = sa2, sigma = c(sig), name = "lowdim")
```

```{r save}
saveRDS(tdat1, "mr.ash.all.RDS")
```