---
title: "Figures_for_the_paper"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(mr.ash.alpha); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
```

```{r fig0.1}
scad = function(b, lambda = 1, gamma = 3) {
  b1 = pmax(abs(b) - lambda, 0) * sign(b) * (abs(b) <= 2 * lambda)
  b2 = ((gamma-1) * b - sign(b) * gamma * lambda) / (gamma-2) * (abs(b) <= gamma * lambda) * (abs(b) > 2 * lambda)
  b3 = b * (abs(b) > gamma * lambda)
  return (b1+b2+b3)
}

mcp = function(b, lambda = 1, gamma = 2) {
  b1 = pmax(abs(b) - lambda, 0) * sign(b) * (b <= gamma * lambda) * gamma / (gamma-1)
  b2 = b * (abs(b) > gamma * lambda)
  return (b1+b2)
}

softt = function(b, lambda = 1) {
  return (pmax(abs(b) - lambda, 0) * sign(b))
}

hardt = function(b, lambda = 1) {
  return (b * (abs(b) >= lambda))
}

postmean = function(b, pi, sa2 = 0:100, sigma2 = 1){
  phi = outer(b^2, 1 / 2 / (1 + 1 / sa2) / sigma2);
  phi = exp(phi - apply(phi, 1, max))
  
  phi = t(pi * t(phi) / sqrt(1 + sa2));
  phi = phi / rowSums(phi);
  out = c(colSums(t(phi) / (1 + 1 / sa2))) * b
  return (out)
}

sa2 = 0:100; b = seq(0,10,0.001)

pi = exp(-sa2)
pi = pi / sum(pi)
b_softt = postmean(b, pi)

pi = double(101)
pi[1] = 0.8; pi[101] = 0.2
b_mcp = postmean(b, pi)

pi = double(101)
pi[1] = 0.6; pi[101] = 0.4
b_hardt = postmean(b, pi, sa2 = sa2^5)

pi = double(101)
pi[1] = 0.5; pi[2:51] = 0.2/50; pi[101] = 0.3
b_scad = postmean(b, pi, sa2 = sa2)
df = data.frame(b = c(b,b,b,b), sb = c(b_softt, b_hardt, b_scad, b_mcp),
                sb2 = c(softt(b, lambda = 1.43),
                        hardt(b, lambda = 5),
                        scad(b, lambda = 1, gamma = 4),
                        mcp(b, lambda = 2)),
                operator = rep(c("soft","hard","scad","mcp"), each = length(b)))
df$operator = factor(df$operator, levels = c("soft","hard","scad","mcp"))

p1 = ggplot(df) + geom_line(aes(x = b, y = sb, color = operator), size = 0.9) +
  theme_cowplot(font_size = 14) + theme(axis.line = element_blank()) +
  labs(y = "shrinkage S(b) of b", title = "MR.ASH shrinkage operators") +
  theme(legend.position = "none")
p2 = ggplot(df) + geom_line(aes(x = b, y = sb2, color = operator), size = 0.9) +
  theme_cowplot(font_size = 14) + theme(axis.line = element_blank()) +
  labs(title = "123")  +
  labs(y = "shrinkage S(b) of b", title = "Well-known shrinkage/thresholding operators")

fig = plot_grid(p1,p2, nrow = 1, rel_widths = c(0.463,0.5))
#title = ggdraw() + draw_label("MR.ASH Shrinkage operator may resemble the well-known shrinkage operators", fontface = 'bold', size = 20) 
#fig = plot_grid(title, fig, nrow = 2, rel_heights = c(0.06,0.95))
ggsave("figures/figure0_paper.pdf", fig, width = 18, height = 7)
```

```{r fig0.2}
l = readRDS("results/CaisaMethods.RDS")

fig1 = my.line(l[[1]]$df, "x", "y", col = gg_color_hue(3), shapes = c(1,2,3)) +
  coord_cartesian(xlim = c(0,100), ylim = c(0,200)) +
  labs(y = "distance from the solution", x = "iteration",
       title = "p = 20000, rho = 0") +
  theme(axis.line    = element_blank(), plot.title = element_text(hjust = 0.5),
        legend.position = "none")
fig2 = my.line(l[[2]]$df, "x", "y", col = gg_color_hue(3), shapes = c(1,2,3)) +
  coord_cartesian(xlim = c(0,100), ylim = c(0,200)) +
  labs(y = "distance from the solution", x = "iteration",
       title = "p = 20000, rho = 0") +
  theme(axis.line    = element_blank(), plot.title = element_text(hjust = 0.5))
fig3 = my.line(l[[3]]$df, "x", "y", col = gg_color_hue(3), shapes = c(1,2,3)) +
  coord_cartesian(xlim = c(0,100), ylim = c(0,200)) +
  labs(y = "distance from the solution", x = "iteration",
       title = "p = 2000, rho = 0.9") +
  theme(axis.line    = element_blank(), plot.title = element_text(hjust = 0.5),
        legend.position = "none")
title     = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, s = 20, pve = 0.5", fontface = 'bold', size = 20) 
fig = plot_grid(title, plot_grid(fig3,fig1,fig2, nrow = 1, rel_widths = c(0.4,0.4,0.5)), nrow = 2, rel_heights = c(0.06,0.95))
ggsave("figures/figure12_paper.pdf", fig, width = 18, height = 8)
```

```{r fig1, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/sparsity500200.RDS")
out = matrix(0,8,15)
lower = matrix(0,8,15)
upper = matrix(0,8,15)
for (i in 1:8) {
  out[i,] = colMeans(matrix(res_df[[i]]$pred, 20, 15))
  lower[i,] = apply(matrix(res_df[[i]]$pred, 20, 15), 2, function(x) quantile(x, probs = 0.1))
  upper[i,] = apply(matrix(res_df[[i]]$pred, 20, 15), 2, function(x) quantile(x, probs = 0.9))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2","Mr.ASH.opt")
ind = 1:12
out = out[,ind]
lower = lower[,ind]
upper = upper[,ind]
s_range = c(1,2,5,10,20,50,100,200)
col   = gg_color_hue(13)[1:12]
shape = c(19,17,24,25,9,3,11,4,5,7,8,1)
df = data.frame(s = rep(s_range, length(ind)), pred = c(out), fit = rep(colnames(out), each = 8),
                lower = c(lower), upper = c(upper))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn",
                                    "VarBVS","BayesB","Blasso","SuSiE","Mr.ASH.opt"))
df$size = 0.5
df$size[1:9] = 1.2
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn"),]
p1 = ggplot(df) + geom_line(aes(x = s, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = s, y = pred, color = fit, shape = fit), size = 3) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = c(1,2,5,10,20,50,100,200)) +
  labs(y = "predictior error (rmse / sigma)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.35))
fig_main = p1
suptitle  = ggdraw() + draw_label("Varying Sparsity, Low-dimensional Setting", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.5", fontface  = 'bold', size = 14) 
fig1      = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig1.1, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/sparsity50010000.RDS")
out = matrix(0,7,15)
lower = matrix(0,7,15)
upper = matrix(0,7,15)
for (i in 1:7) {
  out[i,] = colMeans(matrix(res_df[[i]]$pred, 20, 15))
  lower[i,] = apply(matrix(res_df[[i]]$pred, 20, 15), 2, function(x) quantile(x, probs = 0.1))
  upper[i,] = apply(matrix(res_df[[i]]$pred, 20, 15), 2, function(x) quantile(x, probs = 0.9))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2","Mr.ASH.opt")
ind = 1:12
out = out[,ind]
lower = lower[,ind]
upper = upper[,ind]
s_range = c(1,5,20,100,500,2000,10000)
col   = gg_color_hue(13)[1:12]
shape = c(19,17,24,25,9,3,11,4,5,7,8,1)
df = data.frame(s = rep(s_range, length(ind)), pred = c(out), fit = rep(colnames(out), each = 7),
                lower = c(lower), upper = c(upper))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn",
                                    "VarBVS","BayesB","Blasso","SuSiE","Mr.ASH.opt"))
df$size = 0.5
df$size[1:9] = 1.2
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn"),]
df = df[df$s %in% c(1,5,20,100,500,10000), ]
p1 = ggplot(df) + geom_line(aes(x = s, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = s, y = pred, color = fit, shape = fit), size = 3) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = s_range) +
  labs(y = "predictior error (rmse / sigma)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.45))
fig_main = p1
suptitle  = ggdraw() + draw_label("Varying Sparsity, High-dimensional Setting", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 10000, s = 1-10000, pve = 0.5", fontface  = 'bold', size = 14) 
fig1.1    = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig2, fig.height=11, fig.width=15}
res_df       = readRDS("results/signalshape50020020.RDS")
method_list  = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
col          = gg_color_hue(13)[1:11]
x_range      = 2^(c(1,2,4,5,3,6,7,8) - 1)
df           = data.frame()
for (i in 1:8) {
res_df[[i]]       = res_df[[i]][c(1:20,101:220),]
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_level)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 7))),
                                         df   = x_range[i],
                                         fit  = method_list))
}
df$size = 0.5
df$size[1:8] = 1.2
df$fit = factor(df$fit, levels = method_level)
col   = gg_color_hue(13)[1:7]
shape = c(19,17,24,25,9,3,11,4,5,7,8,1)[1:7]
p1    = ggplot(df) + geom_line(aes(x = df, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = df, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = c(1,2,4,8,16,32,64,128),
                     labels = c("t (df=1)","t (df=2)","Laplace","t (df=4)","t (df=8)",
                                "Normal","Uniform","Constant")) +
  labs(y = "predictior error (rmse / sigma)", x = "distribution of nonzero coefficients") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.4))
fig_main = p1
suptitle  = ggdraw() + draw_label("Varying Signal Shape (or Sampling Distribution of Regression Coefficients)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + Spike-and-Slab, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig2      = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig2.1, fig.height=11, fig.width=15}
res_df       = readRDS("results/signalshape500200020.RDS")
method_list  = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
col          = gg_color_hue(13)[1:11]
x_range      = 2^(c(1,2,4,5,3,6,7,8) - 1)
df           = data.frame()
for (i in 1:8) {
res_df[[i]]       = res_df[[i]][c(1:20,101:220),]
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_level)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 7))),
                                         df   = x_range[i],
                                         fit  = method_list))
}
df$size = 0.5
df$size[1:8] = 1.2
df$fit = factor(df$fit, levels = method_level)
col   = gg_color_hue(13)[1:7]
shape = c(19,17,24,25,9,3,11,4,5,7,8,1)[1:7]
p1    = ggplot(df) + geom_line(aes(x = df, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = df, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = c(1,2,4,8,16,32,64,128),
                     labels = c("t (df=1)","t (df=2)","Laplace","t (df=4)","t (df=8)",
                                "Normal","Uniform","Constant")) +
  labs(y = "predictior error (rmse / sigma)", x = "distribution of nonzero coefficients") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.4))
fig_main = p1
suptitle  = ggdraw() + draw_label("Varying Signal Shape (or Sampling Distribution of Regression Coefficients)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + Spike-and-Slab, n = 500, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig2.1    = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig3, fig.height=11, fig.width=15}
res_df       = readRDS("results/pve50020020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[1:11]
shape        = c(19,17,24,25,9,3,11,4,5,7,8)
pve_list     = seq(0,0.9,0.1)
sdat         = data.frame()
for (i in 1:10) {
  sdat = rbind(sdat, data.frame(pred = colMeans(matrix(res_df[[i]]$pred, 20, 11)),
                                time = colMeans(matrix(res_df[[i]]$time, 20, 11)),
                                fit  = method_list,
                                pve  = pve_list[i]))
}
sdat$fit = factor(sdat$fit, levels = method_level)
sdat     = sdat[sdat$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn"),]
sdat$size = 0.5
sdat$size[1:10] = 1.2

p1 = ggplot(sdat) + geom_line(aes(x = pve, y = pred, color = fit), size = sdat$size) +
  geom_point(aes(x = pve, y = pred, color = fit, shape = fit), size = 2.5) +
  scale_x_continuous(breaks = pve_list) +
  theme_cowplot(font_size = 14) +
  labs(y = "predictior error (rmse / sigma)", x = "proportion of variance explained (pve)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.35))

suptitle  = ggdraw() + draw_label("Varying PVE (or SNR, Noise Variance)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0-0.9", fontface  = 'bold', size = 14) 
fig3      = plot_grid(suptitle, subtitle,p1, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig3.1, fig.height=11, fig.width=15}
res_df       = readRDS("results/pve500200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[1:11]
shape        = c(19,17,24,25,9,3,11,4,5,7,8)
pve_list     = seq(0,0.9,0.1)
sdat         = data.frame()
for (i in 1:10) {
  sdat = rbind(sdat, data.frame(pred = colMeans(matrix(res_df[[i]]$pred, 20, 11)),
                                time = colMeans(matrix(res_df[[i]]$time, 20, 11)),
                                fit  = method_list,
                                pve  = pve_list[i]))
}
sdat$fit = factor(sdat$fit, levels = method_level)
sdat     = sdat[sdat$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn"),]
sdat$size = 0.5
sdat$size[1:10] = 1.2

p1 = ggplot(sdat) + geom_line(aes(x = pve, y = pred, color = fit), size = sdat$size) +
  geom_point(aes(x = pve, y = pred, color = fit, shape = fit), size = 2.5) +
  scale_x_continuous(breaks = pve_list) +
  theme_cowplot(font_size = 14) +
  labs(y = "predictior error (rmse / sigma)", x = "proportion of variance explained (pve)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.35))

suptitle  = ggdraw() + draw_label("Varying PVE (or SNR, Noise Variance)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 2000, s = 20, pve = 0-0.9", fontface  = 'bold', size = 14) 
fig3.1    = plot_grid(suptitle, subtitle,p1, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig4, fig.height=11, fig.width=15}
res_df       = readRDS("results/highdim50020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn")
df           = data.frame()
p_range      = c(20,50,100,200,500,1000,2000,5000,10000,20000)
for (i in 1:10) {
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_list)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 13))),
                                         time2 = apply(matrix(res_df[[i]]$time, 20, 13), 2, median),
                                         time = c(colMeans(matrix(res_df[[i]]$time, 20, 13))),
                                         p    = p_range[i],
                                         fit  = method_list))
}
df$fit = factor(df$fit, levels = method_list)
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]
df = df[df$p %in% c(20,50,200,500,1000,2000,10000,20000),]
df$size = 0.5
df$size[1:8] = 1.2
col   = gg_color_hue(13)[1:7]
shape = c(19,17,24,25,9,3,11,4,5,7,8,1,2,6)[1:7]
p1    = ggplot(df) + geom_line(aes(x = p, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = p, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = c(20,50,200,500,1000,2000,10000,20000)) +
  labs(y = "predictior error (rmse / sigma)", x = "number of coefficients (p)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.2))
fig_main = p1
suptitle  = ggdraw() + draw_label("Varying p", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 20-20000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig4     = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig4.1, fig.height=11, fig.width=15}
res_df       = readRDS("results/highdim50020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn")
df           = data.frame()
p_range      = c(20,50,100,200,500,1000,2000,5000,10000,20000)
for (i in 1:10) {
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_list)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 13))),
                                         time2 = apply(matrix(res_df[[i]]$time, 20, 13), 2, median),
                                         time = c(colMeans(matrix(res_df[[i]]$time, 20, 13))),
                                         p    = p_range[i],
                                         fit  = method_list))
}
df$fit = factor(df$fit, levels = method_list)
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn"),]
df = df[df$p %in% c(20,50,200,500,1000,2000,10000,20000),]
df$size = 0.5
df$size[1:8] = 1.2
col   = gg_color_hue(13)[c(1:6,5,6,7)]
df$lt = "solid"
df$lt[49:64] = "dotted"
shape = c(19,17,24,25,9,3,11,4,5,7,8,1,2,6)[c(1:6,5,6,7)]
p1    = ggplot(df) + geom_line(aes(x = p, y = pred, color = fit), size = df$size, linetype = df$lt) +
  geom_point(aes(x = p, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = c(20,50,200,500,1000,2000,10000,20000)) +
  labs(y = "predictior error (rmse / sigma)", x = "number of coefficients (p)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.3))
fig_main = p1
suptitle  = ggdraw() + draw_label("Varying p", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 20-20000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig4.1    = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig5, fig.height=11, fig.width=15}
res_df = readRDS("results/sparse50010000.RDS")
out = matrix(0,5,15)
for (i in 1:5) {
  out[i,] = colMeans(matrix(res_df[[i]]$pred, 20, 15))
}
s_range       = c(1,10,100,1000,10000)
method_list   = c("varbvs","bayesb","blasso","susie","enet","lasso","ridge","scad2","mcp2","l0learn")
method_list2  = c("mr.ash",method_list,"enet2","lasso2","ridge2","mr.ash.opt")
colnames(out) = method_list2
out           = out[,c(1:11,15)]
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn","Mr.ASH.opt")
ind = c(1,6:11)
out = out[,ind]

col   = gg_color_hue(13)[c(1:7,13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,2,1)[c(1:7,13)]
df = data.frame(s = rep(s_range, length(ind)), pred = c(out), fit = rep(colnames(out), each = 5))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2",
                                    "VarBVS","BayesB","Blasso","SuSiE","Mr.ASH.opt"))
df$size = 0.5
df$size[1:5] = 1.2
p1 = ggplot(df) + geom_line(aes(x = s, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = s, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = s_range) +
  labs(y = "predictior error (rmse / sigma)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.47))
fig_main  = p1
suptitle  = ggdraw() + draw_label("Varying Sparsity, High-dimensional Setting", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 10000, s = 1-10000, pve = 0.5", fontface  = 'bold', size = 14) 
fig5      = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig6, fig.height=11, fig.width=15}
res_df       = readRDS("results/ecorr50020020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn",
                 "Mr.ASH.order","Mr.ASH.init")
method_level = c("Mr.ASH","Mr.ASH.order","Mr.ASH.init","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[c(1,12,13,2:11)]
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,13)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 20, 13))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn",
                  "Mr.ASH.order",
                  "Mr.ASH.init")
ind = c(1,6:13)
out = out[,ind]

col   = gg_color_hue(13)[c(1:7,12:13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12:13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2",
                                    "VarBVS","BayesB","Blasso","SuSiE",
                                    "Mr.ASH.order",
                                    "Mr.ASH.init"))
df$size = 0.5
df$size[1:length(rho_list)] = 1.2
df$lt = "solid"
df$lt[43:48] = "dashed"
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit), size = df$size, linetype = df$lt) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.2))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
suptitle  = ggdraw() + draw_label("Varying Correlation", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig6      = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig6.1, fig.height=11, fig.width=15}
res_df       = readRDS("results/ecorr500200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn",
                 "Mr.ASH.order","Mr.ASH.init")
method_level = c("Mr.ASH","Mr.ASH.order","Mr.ASH.init","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[c(1,12,13,2:11)]
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,13)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 20, 13))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn",
                  "Mr.ASH.order",
                  "Mr.ASH.init")
ind = c(1,6:13)
out = out[,ind]

col   = gg_color_hue(13)[c(1:7,12:13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12:13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2",
                                    "VarBVS","BayesB","Blasso","SuSiE",
                                    "Mr.ASH.order",
                                    "Mr.ASH.init"))
df$size = 0.5
df$size[1:length(rho_list)] = 1.2
df$lt = "solid"
df$lt[43:48] = "dashed"
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit), size = df$size, linetype = df$lt) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.2))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
suptitle  = ggdraw() + draw_label("Varying Correlation", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig6.1    = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig7, fig.height=11, fig.width=15}
res_df       = readRDS("results/localcorr20.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn",
                 "Mr.ASH.order","Mr.ASH.init")
method_level = c("Mr.ASH","Mr.ASH.order","Mr.ASH.init","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[c(1,12,13,2:11)]
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,13)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 20, 13))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn",
                  "Mr.ASH.order",
                  "Mr.ASH.init")
ind = c(1,6:13)
out = out[,ind]

col   = gg_color_hue(13)[c(1:7,12:13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12:13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2",
                                    "VarBVS","BayesB","Blasso","SuSiE",
                                    "Mr.ASH.order",
                                    "Mr.ASH.init"))
df$size = 0.5
df$size[1:length(rho_list)] = 1.2
df$lt = "solid"
df$lt[43:48] = "dashed"
fig_dummy1 = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit), size = df$size, linetype = df$lt) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.12))
p1        = fig_dummy1 + theme(legend.position = "none")
fig_main  = p1
suptitle  = ggdraw() + draw_label("Varying Local Correlation", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: LocalCorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig7      = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig8, fig.height=11, fig.width=15}
res_df       = readRDS("results/highdim50020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn")
df           = data.frame()
p_range      = c(20,50,100,200,500,1000,2000,5000,10000,20000)
for (i in 1:10) {
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_list)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 13))),
                                         time2 = apply(matrix(res_df[[i]]$time, 20, 13), 2, median),
                                         time = c(colMeans(matrix(res_df[[i]]$time, 20, 13))),
                                         p    = p_range[i],
                                         fit  = method_list))
}
df$fit = factor(df$fit, levels = method_list)
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn"),]
df$size = 0.5
df$size[1:5] = 1.2; df$size[46:50] = 1.2;
col   = gg_color_hue(13)[c(1:6,5,6,7)]
df$lt = "solid"
df$lt[c(21:30,66:75)] = "dotted"
shape = c(19,17,24,25,9,3,11,4,5,7,8,1,2,6)[c(1:6,5,6,7)]
p1    = ggplot(df[df$p <= 500, ]) + geom_line(aes(x = p, y = time, color = fit),
                                              size = df$size[df$p <= 500], linetype = df$lt[df$p <= 500]) +
  geom_point(aes(x = p, y = time, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = p_range) +
  labs(y = "compmutation time (seconds)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10")
fig_main = p1
subtitle  = ggdraw() + draw_label("Computation time (log-scale) for p <= n", fontface = 'bold', size = 14) 
title     = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 20-20000, s = 20, pve = 0.5", fontface  = 'bold', size = 20) 
fig8      = plot_grid(subtitle,fig_main, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig9, fig.height=11, fig.width=15}
p2    = ggplot(df[df$p > 500, ]) + geom_line(aes(x = p, y = time, color = fit),
                                             size = df$size[df$p > 500], linetype = df$lt[df$p > 500]) +
  geom_point(aes(x = p, y = time, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = p_range) +
  labs(y = "compmutation time (seconds)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10")
fig_main = p2
subtitle  = ggdraw() + draw_label("Computation time (log-scale) for p > n", fontface = 'bold', size = 14) 
fig9      = plot_grid(subtitle,fig_main, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig8.1, fig.height=11, fig.width=15}
res_df       = readRDS("results/highdim50020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn")
df           = data.frame()
p_range      = c(20,50,100,200,500,1000,2000,5000,10000,20000)
for (i in 1:10) {
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_list)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 13))),
                                         time2 = apply(matrix(res_df[[i]]$time, 20, 13), 2, median),
                                         time = c(colMeans(matrix(res_df[[i]]$time, 20, 13))),
                                         p    = p_range[i],
                                         fit  = method_list))
}
df$fit = factor(df$fit, levels = method_list)
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn"),]
df$size = 0.5
df$size[1:10] = 1.2;
col   = gg_color_hue(13)[c(1:6,5,6,7)]
df$lt = "solid"
df$lt[41:60] = "dotted"
shape = c(19,17,24,25,9,3,11,4,5,7,8,1,2,6)[c(1:6,5,6,7)]
p1    = ggplot(df) + geom_line(aes(x = p, y = time, color = fit),
                                              size = df$size, linetype = df$lt) +
  geom_point(aes(x = p, y = time, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = p_range) +
  labs(y = "compmutation time (seconds)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10")
fig_main = p1
subtitle  = ggdraw() + draw_label("Computation time (log-scale) for p <= n", fontface = 'bold', size = 14) 
title     = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 20-20000, s = 20, pve = 0.5", fontface  = 'bold', size = 20) 
fig8.1    = plot_grid(subtitle,fig_main, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig9.1, fig.height=11, fig.width=15}
res_df       = readRDS("results/highdim50020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn")
df           = data.frame()
p_range      = c(20,50,100,200,500,1000,2000,5000,10000,20000)
for (i in 1:10) {
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_list)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 13))),
                                         time2 = apply(matrix(res_df[[i]]$time, 20, 13), 2, median),
                                         time = c(colMeans(matrix(res_df[[i]]$time, 20, 13))),
                                         p    = p_range[i],
                                         fit  = method_list))
}
df$fit = factor(df$fit, levels = method_list)
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn"),]
df$size = 0.5
df$size[1:5] = 1.2; df$size[46:50] = 1.2;
col   = gg_color_hue(13)[c(1:6,5,6,7)]
df$lt = "solid"
df$lt[c(21:30,66:75)] = "dotted"
shape = c(19,17,24,25,9,3,11,4,5,7,8,1,2,6)[c(1:6,5,6,7)]
p1    = ggplot() + geom_line(aes(x = df$p[df$p <= 500], y = df$time[df$p <= 500], color = df$fit[df$p <= 500]),
                                 size = df$size[df$p <= 500], linetype = df$lt[df$p <= 500]) +
  geom_point(aes(x = df$p[df$p <= 500], y = df$time[df$p <= 500], color = df$fit[df$p <= 500],
                 shape = df$fit[df$p <= 500]), size = 2.5) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape)
fig_main = p1 + geom_line(aes(x = df$p[df$p > 500], y = df$time[df$p > 500], color = df$fit[df$p > 500]),
                              size = df$size[df$p > 500], linetype = df$lt[df$p > 500]) + 
    geom_point(aes(x = df$p[df$p > 500], y = df$time[df$p > 500], color = df$fit[df$p > 500],
                   shape = df$fit[df$p > 500]), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = p_range) +
  labs(y = "computation time (seconds)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_y_continuous(trans = "log10")
subtitle  = ggdraw() + draw_label("", fontface = 'bold', size = 1) 
fig9.1    = plot_grid(subtitle,fig_main, ncol = 1, rel_heights = c(0,0.95))
```

```{r fig10, fig.height=11, fig.width=15, fig.align = "center"}
res_df       = readRDS("results/largen200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
n_range      = c(50,100,200,500,1000,2000,5000)
for (i in 3:7) {
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_list)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 11))),
                                         time2 = apply(matrix(res_df[[i]]$time, 20, 11), 2, median),
                                         time = c(colMeans(matrix(res_df[[i]]$time, 20, 11))),
                                         n    = n_range[i],
                                         fit  = method_list))
}
df$fit = factor(df$fit, levels = method_list)
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]
df$size = 0.5
df$size[1:5] = 1.2
col   = gg_color_hue(13)[1:7]
shape = c(19,17,24,25,9,3,11,4,5,7,8,1,2,6)[1:7]
p1    = ggplot(df) + geom_line(aes(x = n, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = n, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = n_range) +
  labs(y = "predictior error (rmse / sigma)", x = "number of coefficients (p)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 45,hjust = 1)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.4))
fig_dummy2 = p1
fig_main  = p1 + theme(legend.position = "none")
suptitle  = ggdraw() + draw_label("Varying n", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 200-5000, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig10     = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r figure1, fig.height=20, fig.width=16}
figure1  = plot_grid(fig4.1,fig10,fig1,fig1.1, ncol = 2, rel_widths = c(0.5,0.5))
title    = ggdraw() + draw_label("Prediction Error (RMSE / sigma)", fontface = 'bold', size = 20)
legend <- get_legend(fig_dummy2 + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure1  = plot_grid(plot_grid(title, figure1, ncol = 1, rel_heights = c(0.05,0.95)), legend, nrow = 1, rel_widths = c(0.9,0.1))
ggsave("figures/figure1_paper.pdf", figure1, width = 18, height = 15)
```

```{r figure2, fig.height=20, fig.width=16}
figure2  = plot_grid(fig3, fig3.1, fig2,fig2.1,fig6,fig6.1, ncol = 2, rel_widths = c(0.5,0.5))
title    = ggdraw() + draw_label("Prediction Error (RMSE / sigma)", fontface = 'bold', size = 20)
legend <- get_legend(fig_dummy1 + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure2  = plot_grid(plot_grid(title, figure2, ncol = 1, rel_heights = c(0.05,0.95)), legend, nrow = 1, rel_widths = c(0.9,0.1))
ggsave("figures/figure2_paper.pdf", figure2, width = 18, height = 22)
```

#```{r figure3, fig.height=14, fig.width=16}
#p0       = ggplot() + geom_blank() + theme_cowplot() + theme(axis.line = element_blank())
#figure3  = plot_grid(fig8,fig9, nrow = 1)
#title    = ggdraw() + draw_label("Varying p", fontface  = 'bold', size = 18) 
#title2   = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 20-20000, s = 20, pve = 0.5", fontface  = 'bold', #size = 16) 
#legend  <- get_legend(fig_dummy2 + theme(legend.box.margin = margin(0, 0, 0, 12)))
#figure3  = plot_grid(plot_grid(title, title2, figure3, ncol = 1, rel_heights = c(0.04,0.04,0.95)),
#                     legend, nrow = 1, rel_widths = c(0.9,0.1))
#ggsave("figures/figure3_paper.pdf", figure3, width = 18, height = 8)
#```

```{r fig11, fig.height=11, fig.width=15, fig.align = "center"}
res_df       = readRDS("results/sparsity500200.RDS")
out = matrix(0,8,15)
lower = matrix(0,8,15)
upper = matrix(0,8,15)
for (i in 1:8) {
  out[i,] = colMeans(matrix(res_df[[i]]$pred, 20, 15))
  lower[i,] = apply(matrix(res_df[[i]]$pred, 20, 15), 2, function(x) quantile(x, probs = 0.1))
  upper[i,] = apply(matrix(res_df[[i]]$pred, 20, 15), 2, function(x) quantile(x, probs = 0.9))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2","Mr.ASH.opt")
ind = c(1:11,15)
out = out[,ind]
lower = lower[,ind]
upper = upper[,ind]
s_range = c(1,2,5,10,20,50,100,200)
col   = gg_color_hue(13)[c(1,8:11,13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,8:11,13)]
df = data.frame(s = rep(s_range, length(ind)), pred = c(out), fit = rep(colnames(out), each = 8),
                lower = c(lower), upper = c(upper))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn",
                                    "VarBVS","BayesB","Blasso","SuSiE","Mr.ASH.opt"))
df$size = 0.5
df$size[1:8] = 1.2
df = df[df$fit %in% c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE"),]
p1 = ggplot(df) + geom_line(aes(x = s, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = s, y = pred, color = fit, shape = fit), size = 3) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = s_range) +
  labs(y = "predictior error (rmse / sigma)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.35))
fig_main = p1
suptitle  = ggdraw() + draw_label("Varying Sparsity, Low-dimensional Setting", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.5", fontface  = 'bold', size = 14) 
fig11     = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig12, fig.height=11, fig.width=15}
res_df       = readRDS("results/pve50020020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col   = gg_color_hue(13)[c(1,8:11,13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,8:11,13)]
pve_list     = seq(0,0.9,0.1)
sdat         = data.frame()
for (i in 1:10) {
  sdat = rbind(sdat, data.frame(pred = colMeans(matrix(res_df[[i]]$pred, 20, 11)),
                                time = colMeans(matrix(res_df[[i]]$time, 20, 11)),
                                fit  = method_list,
                                pve  = pve_list[i]))
}
sdat$fit = factor(sdat$fit, levels = method_level)
sdat     = sdat[sdat$fit %in% c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE"),]
sdat$size = 0.5
sdat$size[1:10] = 1.2

p1 = ggplot(sdat) + geom_line(aes(x = pve, y = pred, color = fit), size = sdat$size) +
  geom_point(aes(x = pve, y = pred, color = fit, shape = fit), size = 2.5) +
  scale_x_continuous(breaks = pve_list) +
  theme_cowplot(font_size = 14) +
  labs(y = "predictior error (rmse / sigma)", x = "proportion of variance explained (pve)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.3))
suptitle  = ggdraw() + draw_label("Varying PVE (or SNR, Noise Variance)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0-0.9", fontface  = 'bold', size = 14) 
fig12     = plot_grid(suptitle,subtitle,p1, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig12.1, fig.height=11, fig.width=15}
res_df       = readRDS("results/pve500200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col   = gg_color_hue(13)[c(1,8:11,13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,8:11,13)]
pve_list     = seq(0,0.9,0.1)
sdat         = data.frame()
for (i in 1:10) {
  sdat = rbind(sdat, data.frame(pred = colMeans(matrix(res_df[[i]]$pred, 20, 11)),
                                time = colMeans(matrix(res_df[[i]]$time, 20, 11)),
                                fit  = method_list,
                                pve  = pve_list[i]))
}
sdat$fit = factor(sdat$fit, levels = method_level)
sdat     = sdat[sdat$fit %in% c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE"),]
sdat$size = 0.5
sdat$size[1:10] = 1.2

p1 = ggplot(sdat) + geom_line(aes(x = pve, y = pred, color = fit), size = sdat$size) +
  geom_point(aes(x = pve, y = pred, color = fit, shape = fit), size = 2.5) +
  scale_x_continuous(breaks = pve_list) +
  theme_cowplot(font_size = 14) +
  labs(y = "predictior error (rmse / sigma)", x = "proportion of variance explained (pve)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.3))
suptitle  = ggdraw() + draw_label("Varying PVE (or SNR, Noise Variance)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 2000, s = 20, pve = 0-0.9", fontface  = 'bold', size = 14) 
fig12.1   = plot_grid(suptitle,subtitle,p1, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig13, fig.height=11, fig.width=15}
res_df       = readRDS("results/highdim50020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn")
method_level = method_list
col          = gg_color_hue(13)[c(1,8:13)]
shape        = c(19,17,24,25,9,3,11,4,5,7,8,2,1)[c(1,8:13)]
p_range      = c(20,50,100,200,500,1000,2000,5000,10000,20000)
sdat         = data.frame()
for (i in 1:10) {
  sdat = rbind(sdat, data.frame(pred = colMeans(matrix(res_df[[i]]$pred, 20, 13)),
                                time = colMeans(matrix(res_df[[i]]$time, 20, 13)),
                                fit  = method_list,
                                p    = p_range[i]))
}
sdat$fit = factor(sdat$fit, levels = method_level)
sdat     = sdat[sdat$fit %in% c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE"),]
sdat$size = 0.5
sdat$size[1:7] = 1.2
sdat = sdat[sdat$p %in% c(20,50,200,500,1000,2000,10000,20000),]

p1 = ggplot(sdat) + geom_line(aes(x = p, y = pred, color = fit), size = sdat$size) +
  geom_point(aes(x = p, y = pred, color = fit, shape = fit), size = 2.5) +
  scale_x_continuous(trans = "log", breaks = p_range) +
  theme_cowplot(font_size = 14) +
  labs(y = "predictior error (rmse / sigma)", x = "number of nonzero coefficients (p)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.3))
suptitle  = ggdraw() + draw_label("Varying p", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 20-20000, s = 20, pve = 0-0.9", fontface  = 'bold', size = 14) 
fig13      = plot_grid(suptitle,subtitle,p1, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig14, fig.height=11, fig.width=15}
res_df       = readRDS("results/sparsity50010000.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2","Mr.ASH.opt")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE","Mr.ASH.opt")
col          = gg_color_hue(13)[c(1,8:13)]
shape        = c(19,17,24,25,9,3,11,4,5,7,8,2,1)[c(1,8:13)]
s_range      = c(1,5,20,100,500,2000,10000)
sdat         = data.frame()
for (i in 1:7) {
  sdat = rbind(sdat, data.frame(pred = colMeans(matrix(res_df[[i]]$pred, 20, 15)),
                                time = colMeans(matrix(res_df[[i]]$time, 20, 15)),
                                fit  = method_list,
                                s    = s_range[i]))
}
sdat$fit = factor(sdat$fit, levels = method_level)
sdat     = sdat[sdat$fit %in% c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE"),]
sdat$size = 0.5
sdat$size[1:7] = 1.2
sdat = sdat[sdat$s %in% c(1,5,20,100,500,10000), ]

p1 = ggplot(sdat) + geom_line(aes(x = s, y = pred, color = fit), size = sdat$size) +
  geom_point(aes(x = s, y = pred, color = fit, shape = fit), size = 2.5) +
  scale_x_continuous(trans = "log10", breaks = c(1,5,20,100,500,10000)) +
  theme_cowplot(font_size = 14) +
  labs(y = "predictior error (rmse / sigma)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.42))
suptitle  = ggdraw() + draw_label("Varying Sparsity, High-dimensional Setting", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 10000, s = 1-10000, pve = 0.5", fontface  = 'bold', size = 14) 
fig14     = plot_grid(suptitle,subtitle,p1, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig15, fig.height=11, fig.width=15}
res_df       = readRDS("results/localcorr20.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn",
                 "Mr.ASH.order","Mr.ASH.init")
method_level = c("Mr.ASH","Mr.ASH.order","Mr.ASH.init","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[c(1,12,13,2:11)]
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,13)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 20, 13))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn",
                  "Mr.ASH.order",
                  "Mr.ASH.init")
ind = c(1:5,12:13)
out = out[,ind]

col   = gg_color_hue(13)[c(1,8:13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,8:13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2",
                                    "VarBVS","BayesB","Blasso","SuSiE",
                                    "Mr.ASH.order",
                                    "Mr.ASH.init"))
df$size = 0.5
df$size[1:length(rho_list)] = 1.2
df$lt = "solid"
df$lt[31:36] = "dashed"
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit), size = df$size, linetype = df$lt) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.12))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
suptitle  = ggdraw() + draw_label("Varying Local Correlation", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: LocalCorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig15     = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig16, fig.height=11, fig.width=15}
res_df       = readRDS("results/ecorr50020020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn",
                 "Mr.ASH.order","Mr.ASH.init")
method_level = c("Mr.ASH","Mr.ASH.order","Mr.ASH.init","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[c(1,12,13,2:11)]
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,13)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 20, 13))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn",
                  "Mr.ASH.order",
                  "Mr.ASH.init")
ind = c(1:5,12:13)
out = out[,ind]

col   = gg_color_hue(13)[c(1,8:13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,8:13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2",
                                    "VarBVS","BayesB","Blasso","SuSiE",
                                    "Mr.ASH.order",
                                    "Mr.ASH.init"))
df$size = 0.5
df$size[1:length(rho_list)] = 1.2
df$lt = "solid"
df$lt[31:36] = "dashed"
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit), size = df$size, linetype = df$lt) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.2))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
suptitle  = ggdraw() + draw_label("Varying Correlation", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig16     = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig16.1, fig.height=11, fig.width=15}
res_df       = readRDS("results/ecorr500200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn",
                 "Mr.ASH.order","Mr.ASH.init")
method_level = c("Mr.ASH","Mr.ASH.order","Mr.ASH.init","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[c(1,12,13,2:11)]
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,13)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 20, 13))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn",
                  "Mr.ASH.order",
                  "Mr.ASH.init")
ind = c(1:5,12:13)
out = out[,ind]

col   = gg_color_hue(13)[c(1,8:13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,8:13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2",
                                    "VarBVS","BayesB","Blasso","SuSiE",
                                    "Mr.ASH.order",
                                    "Mr.ASH.init"))
df$size = 0.5
df$size[1:length(rho_list)] = 1.2
df$lt = "solid"
df$lt[31:36] = "dashed"
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit), size = df$size, linetype = df$lt) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.3))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
suptitle  = ggdraw() + draw_label("Varying Correlation", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig16.1   = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig17, fig.height=11, fig.width=15}
res_df = readRDS("results/newridge20.RDS")
out = matrix(0,5,15)
for (i in 1:5) {
  out[i,] = colMeans(matrix(res_df[[i]]$pred, 20, 15))
}
s_range       = c(1,10,100,1000,10000)
method_list   = c("varbvs","bayesb","blasso","susie","enet","lasso","ridge","scad2","mcp2","l0learn")
method_list2  = c("mr.ash",method_list,"enet2","lasso2","ridge2","mr.ash.opt")
colnames(out) = method_list2
out           = out[,c(1:11,15)]
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn","Mr.ASH.opt")
ind = c(1:5)
out = out[,ind]

col   = gg_color_hue(13)[c(1,8:11)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,8:11)]
df = data.frame(s = rep(s_range, length(ind)), pred = c(out), fit = rep(colnames(out), each = 5))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2",
                                    "VarBVS","BayesB","Blasso","SuSiE","Mr.ASH.opt"))
df$size = 0.5
df$size[1:5] = 1.2
p1 = ggplot(df) + geom_line(aes(x = s, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = s, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = s_range) +
  labs(y = "predictior error (rmse / sigma)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.47))
fig_main  = p1
suptitle  = ggdraw() + draw_label("Varying Sparsity, High Dimensional Setting", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + Normal, n = 500, p = 10000, s = 1-10000, pve = 0.5", fontface  = 'bold', size = 14) 
fig17     = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig18, fig.height=11, fig.width=15}
res_df       = readRDS("results/signalshape50020020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE")
method_level = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE")
df           = data.frame()
for (i in 1:8) {
res_df[[i]]       = res_df[[i]][1:100,]
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_level)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 5))),
                                         df   = x_range[i],
                                         fit  = method_list))
}
df$size = 0.5
df$size[1:8] = 1.2
df$fit = factor(df$fit, levels = method_level)
col   = gg_color_hue(13)[c(1,8:11,13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,2,1)[c(1,8:11,13)]
p1    = ggplot(df) + geom_line(aes(x = df, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = df, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = c(1,2,4,8,16,32,64,128),
                     labels = c("t (df=1)","t (df=2)","Laplace","t (df=4)","t (df=8)",
                                "Normal","Uniform","Constant")) +
  labs(y = "predictior error (rmse / sigma)", x = "distribution of nonzero coefficients") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.35))
fig_main = p1
suptitle  = ggdraw() + draw_label("Varying Signal Shape (or Sampling Distribution of Regression Coefficients)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + Spike-and-Slab, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig18     = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig18.1, fig.height=11, fig.width=15}
res_df       = readRDS("results/signalshape500200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE")
df           = data.frame()
for (i in 1:8) {
res_df[[i]]       = res_df[[i]][1:200,]
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_level)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 5))),
                                         df   = x_range[i],
                                         fit  = method_list))
}
df$size = 0.5
df$size[1:8] = 1.2
df$fit = factor(df$fit, levels = method_level)
col   = gg_color_hue(13)[c(1,8:11)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,8:11)]
p1    = ggplot(df) + geom_line(aes(x = df, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = df, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = c(1,2,4,8,16,32,64,128),
                     labels = c("t (df=1)","t (df=2)","Laplace","t (df=4)","t (df=8)",
                                "Normal","Uniform","Constant")) +
  labs(y = "predictior error (rmse / sigma)", x = "distribution of nonzero coefficients") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.4))
fig_main = p1
suptitle  = ggdraw() + draw_label("Varying Signal Shape (or Sampling Distribution of Regression Coefficients)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + Spike-and-Slab, n = 500, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig18.1   = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig19, fig.height=11, fig.width=15}
res_df       = readRDS("results/highdim50020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn")
method_level = method_list
col          = gg_color_hue(13)[c(1,8:13)]
shape        = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,8:13)]
p_range      = c(20,50,100,200,500,1000,2000,5000,10000,20000)
sdat         = data.frame()
for (i in 1:10) {
  sdat = rbind(sdat, data.frame(pred = colMeans(matrix(res_df[[i]]$pred, 20, 13)),
                                time = colMeans(matrix(res_df[[i]]$time, 20, 13)),
                                fit  = method_list,
                                p    = p_range[i]))
}
sdat$fit = factor(sdat$fit, levels = method_level)
sdat     = sdat[sdat$fit %in% c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE"),]
sdat$size = 0.5
sdat$size[1:10] = 1.2

p1 = ggplot(sdat) + geom_line(aes(x = p, y = time, color = fit), size = sdat$size) +
  geom_point(aes(x = p, y = time, color = fit, shape = fit), size = 2.5) +
  scale_x_continuous(trans = "log", breaks = p_range) +
  theme_cowplot(font_size = 14) +
  labs(y = "computation time (seconds)", x = "number of nonzero coefficients (p)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10")
fig_dummy3 = p1
fig19      = p1 + theme(legend.position = "none")
#fig19      = plot_grid(subtitle,fig_main, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig19.1, fig.height=11, fig.width=15}
res_df       = readRDS("results/highdim50020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","SCAD2","MCP2","L0Learn","VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[c(1:6,5,6,7:11)]
shape        = c(19,17,24,25,9,3,11,4,5,7,8,2,1)[c(1:6,5,6,7:11)]
p_range      = c(20,50,100,200,500,1000,2000,5000,10000,20000)
sdat         = data.frame()
for (i in 1:10) {
  sdat = rbind(sdat, data.frame(pred = colMeans(matrix(res_df[[i]]$pred, 20, 13)),
                                time = colMeans(matrix(res_df[[i]]$time, 20, 13)),
                                fit  = method_list,
                                p    = p_range[i]))
}
sdat$fit = factor(sdat$fit, levels = method_level)
sdat$size = 0.5
sdat$size[1:10] = 1.2

fig_dummy4 = ggplot(sdat) + geom_line(aes(x = p, y = time, color = fit), size = sdat$size) +
  geom_point(aes(x = p, y = time, color = fit, shape = fit), size = 2.5) +
  scale_x_continuous(trans = "log", breaks = p_range) +
  theme_cowplot(font_size = 14) +
  labs(y = "computation time (seconds)", x = "number of nonzero coefficients (p)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10")
```

```{r fig20, fig.height=11, fig.width=15, fig.align = "center"}
res_df       = readRDS("results/largen200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
n_range      = c(50,100,200,500,1000,2000,5000)
for (i in 3:7) {
res_df[[i]]$fit   = rep(method_list, each = 20)
res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_list)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 11))),
                                         time2 = apply(matrix(res_df[[i]]$time, 20, 11), 2, median),
                                         time = c(colMeans(matrix(res_df[[i]]$time, 20, 11))),
                                         n    = n_range[i],
                                         fit  = method_list))
}
df$fit = factor(df$fit, levels = method_list)
df = df[df$fit %in% c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE"),]
df$size = 0.5
df$size[1:5] = 1.2
col   = gg_color_hue(13)[c(1,8:11)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,2,1)[c(1,8:11)]
p1    = ggplot(df) + geom_line(aes(x = n, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = n, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = n_range) +
  labs(y = "predictior error (rmse / sigma)", x = "number of coefficients (p)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 45,hjust = 1)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.4))
fig_dummy2 = p1
fig_main  = p1 + theme(legend.position = "none")
suptitle  = ggdraw() + draw_label("Varying n", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 200-5000, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig20     = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r figure4, fig.height=20, fig.width=16}
figure4  = plot_grid(fig13,fig20,fig11,fig14, ncol = 2, rel_widths = c(0.5,0.5))
title    = ggdraw() + draw_label("Prediction Error (RMSE / sigma)", fontface = 'bold', size = 20)
legend <- get_legend(fig_dummy3 + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure4  = plot_grid(plot_grid(title, figure4, ncol = 1, rel_heights = c(0.05,0.95)), legend, nrow = 1, rel_widths = c(0.9,0.1))
ggsave("figures/figure4_paper.pdf", figure4, width = 18, height = 15)
```

```{r figure5, fig.height=20, fig.width=16}
figure5  = plot_grid(fig12,fig12.1,fig18,fig18.1,fig16,fig16.1, ncol = 2, rel_widths = c(0.5,0.5))
title    = ggdraw() + draw_label("Prediction Error (RMSE / sigma)", fontface = 'bold', size = 20)
legend <- get_legend(fig_dummy + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure5  = plot_grid(plot_grid(title, figure5, ncol = 1, rel_heights = c(0.05,0.95)), legend, nrow = 1, rel_widths = c(0.9,0.1))
ggsave("figures/figure5_paper.pdf", figure5, width = 18, height = 22)
```

```{r figure6, fig.height=14, fig.width=16}
p0       = ggplot() + geom_blank() + theme_cowplot() + theme(axis.line = element_blank())
figure6  = plot_grid(fig9.1,fig19, nrow = 1)
title    = ggdraw() + draw_label("Computation time with varying p", fontface  = 'bold', size = 18) 
title2   = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 20-20000, s = 20, pve = 0.5", fontface  = 'bold', size = 16) 
legend  <- get_legend(fig_dummy4 + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure6  = plot_grid(plot_grid(title, title2, figure6, ncol = 1, rel_heights = c(0.04,0.04,0.95)),
                     legend, nrow = 1, rel_widths = c(0.9,0.1))
ggsave("figures/figure6_paper.pdf", figure6, width = 18, height = 8)
```

```{r fig31, fig.height=11, fig.width=15}
res_df       = readRDS("results/mcmc50020.RDS")
method_list  = c("Mr.ASH","BayesB","bayesc","MCMC","BayesB2","bayesc2","MCMC2","Mr.ASH.g","Mr.ASH.g.init")
method_level = c("Mr.ASH","Mr.ASH.g","Mr.ASH.g.init","BayesB","BayesB2","bayesc","bayesc2","MCMC","MCMC2")
df           = data.frame()
p_range      = c(20,50,200,500,2000,10000)
for (i in 1:6) {
res_df[[i]]$fit   = rep(method_list, each = 20)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 9))),
                                         time2 = apply(matrix(res_df[[i]]$time, 20, 9), 2, median),
                                         time = c(colMeans(matrix(res_df[[i]]$time, 20, 9))),
                                         p    = p_range[i],
                                         fit  = method_list))
}
df$fit = factor(df$fit, levels = method_level)
col   = c(gg_color_hue(13)[1],"orange","darkblue","dodgerblue","darkgreen","limegreen","gold","salmon","skyblue")
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,12,3,4,5,6)]
df    = df[df$fit %in% c("Mr.ASH","Mr.ASH.g","BayesB","BayesB2","MCMC","MCMC2"),]
p1    = ggplot(df) + geom_line(aes(x = p, y = pred, color = fit)) +
  geom_point(aes(x = p, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = c(20,50,200,500,2000,10000)) +
  labs(y = "predictior error (rmse / sigma)", x = "number of coefficients (p)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 45,hjust = 1)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.3)) +
  coord_cartesian(ylim = c(1,1.15))
fig_main = p1 + theme(legend.position = "none")
title     = ggdraw() + draw_label("Varying p", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 20-10000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig31     = plot_grid(title,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig32, fig.height=11, fig.width=15}
res_df       = readRDS("results/mcmcecorr50020020.RDS")
res_df1      = readRDS("results/equicorr50020020.RDS")
for (i in 1:6) {
  res_df[[i]][1:20,] = res_df1[[i]][1:20, ]
  res_df[[i]]        = rbind(res_df[[i]], res_df1[[i]][241:260,])
}
method_list  = c("Mr.ASH","BayesB","bayesc","MCMC","BayesB2","bayesc2","MCMC2","Mr.ASH.g","Mr.ASH.g.init","Mr.ASH.init")
method_level = c("Mr.ASH","Mr.ASH.g","Mr.ASH.init","Mr.ASH.g.init","BayesB","BayesB2","bayesc","bayesc2","MCMC","MCMC2")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,10)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 20, 10))
}
colnames(out) = method_list
ind = 1:10
out = out[,ind]

col   = c(gg_color_hue(13)[1],gg_color_hue(13)[13],"orange","darkblue",
          "dodgerblue","darkgreen","limegreen","gold","orange","salmon","skyblue")
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,13,12,3,4,5,6)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels =  method_level)
df    = df[df$fit %in% c("Mr.ASH","Mr.ASH.init","Mr.ASH.g.init","BayesB","BayesB2","MCMC","MCMC2"),]
df$size = 0.5
df$size[1:length(rho_list)] = 1.2
fig_dummy5 = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.25,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.2))
p1        = fig_dummy5 + theme(legend.position = "none")
fig_main  = p1
title     = ggdraw() + draw_label("Varying Correlation", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig32     = plot_grid(title,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig33, fig.height=11, fig.width=15}
res_df       = readRDS("results/initialization50020020.RDS")
res_df1      = readRDS("results/initialization500200020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:3
out = matrix(0,6,6)
for (i in 1:6) {
  out[i,] = c(colMeans(matrix(res_df[[a[i]]]$pred, 100, 3))[c(1,2,3)],
              colMeans(matrix(res_df1[[a[i]]]$pred, 100, 3))[c(1,2,3)])
}
col   = gg_color_hue(13)[c(1,5,3)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,5,3)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                p = factor(rep(c(200,2000), each = 6 * 3)),
                pred = c(out), fit = rep(c("null","scad","lasso","null","scad","lasso"), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("null","scad","lasso"))
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit, linetype = p)) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.25,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.12))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + Normal, n = 500, p = 200 or 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig33     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig34, fig.height=11, fig.width=15}
res_df       = readRDS("results/initialization50020020.RDS")
res_df1      = readRDS("results/initialization500200020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,6)
for (i in 1:6) {
  out[i,] = c(colMeans(matrix(res_df[[a[i]]]$vobj, 100, 3)[,1] - matrix(res_df[[a[i]]]$vobj, 100, 3))[c(1,2,3)],
              colMeans(matrix(res_df1[[a[i]]]$vobj, 100, 3)[,1] - matrix(res_df1[[a[i]]]$vobj, 100, 3))[c(1,2,3)])
}
ind   = 1:3
col   = gg_color_hue(13)[c(1,5,3)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,5,3)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                p = factor(rep(c(200,2000), each = length(rho_list) * 3)),
                vobj = c(out), fit = rep(c("null","scad","lasso","null","scad","lasso"), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("null","scad","lasso"))
fig_dummy6 = ggplot(df) + geom_line(aes(x = x, y = vobj, color = fit, linetype = p)) +
  geom_point(aes(x = x, y = vobj, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "variational objective difference (ELBO - ELBO_null)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape)
p1        = fig_dummy6 + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + Normal, n = 500, p = 200 or 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig34     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig35, fig.height=11, fig.width=15}
res_df       = readRDS("results/updateorder50020020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:7
out = matrix(0,6,7)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 100, 7))
}
colnames(out) = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                  "lasso.abs.order","random.permuted","true.abs.order")

col   = c(gg_color_hue(13)[1],"darkblue","dodgerblue","darkgreen","limegreen","orange","gold2")
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12,13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                                   "lasso.abs.order","random.permuted","true.abs.order")
)
fig_dummy7 = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit)) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.25,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.1))
p1        = fig_dummy7 + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig35     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig36, fig.height=11, fig.width=15}
res_df       = readRDS("results/updateorder500200020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:7
out = matrix(0,6,7)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 100, 7))
}
colnames(out) = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                  "lasso.abs.order","random.permuted","true.abs.order")

col   = c(gg_color_hue(13)[1],"darkblue","dodgerblue","darkgreen","limegreen","orange","gold2")
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12,13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                                   "lasso.abs.order","random.permuted","true.abs.order")
)
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit)) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.25,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.15))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig36     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig37, fig.height=11, fig.width=15}
res_df       = readRDS("results/updateorder50020020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:7
out = matrix(0,6,7)
for (i in 1:6) {
  out[i,] = -colMeans(matrix(res_df[[a[i]]]$vobj, 100, 7) - matrix(res_df[[a[i]]]$vobj, 100, 7)[,6])
}
colnames(out) = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                  "lasso.abs.order","random.permuted","true.abs.order")

col   = c(gg_color_hue(13)[1],"darkblue","dodgerblue","darkgreen","limegreen","orange","gold2")
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12,13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                vobj = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                                   "lasso.abs.order","random.permuted","true.abs.order")
)
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = vobj, color = fit)) +
  geom_point(aes(x = x, y = vobj, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "variational objective difference (ELBO - ELBO_null)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape)
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig37     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig38, fig.height=11, fig.width=15}
res_df       = readRDS("results/updateorder500200020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:7
out = matrix(0,6,7)
for (i in 1:6) {
  out[i,] = -colMeans(matrix(res_df[[a[i]]]$vobj, 100, 7) - matrix(res_df[[a[i]]]$vobj, 100, 7)[,6])
}
colnames(out) = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                  "lasso.abs.order","random.permuted","true.abs.order")

col   = c(gg_color_hue(13)[1],"darkblue","dodgerblue","darkgreen","limegreen","orange","gold2")
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12,13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                vobj = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                                   "lasso.abs.order","random.permuted","true.abs.order")
)
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = vobj, color = fit)) +
  geom_point(aes(x = x, y = vobj, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "variational objective difference (ELBO - ELBO_null)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape)
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig38     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r figure3, fig.height=14, fig.width=16}
p0       = ggplot() + geom_blank() + theme_cowplot() + theme(axis.line = element_blank())
figure3  = plot_grid(fig31,fig32, nrow = 1)
title    = ggdraw() + draw_label("Accuracy of Variational Approximation", fontface = 'bold', size = 20) 
legend  <- get_legend(fig_dummy5 + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure3  = plot_grid(plot_grid(title, figure3, ncol = 1, rel_heights = c(0.04,0.95)),
                     legend, nrow = 1, rel_widths = c(0.9,0.1))
ggsave("figures/figure3_paper.pdf", figure3, width = 18, height = 8)
```

```{r figure7, fig.height=14, fig.width=16}
p0       = ggplot() + geom_blank() + theme_cowplot() + theme(axis.line = element_blank())
figure7  = plot_grid(fig33,fig34, nrow = 1)
title    = ggdraw() + draw_label("Initialization of MR.ASH", fontface = 'bold', size = 20) 
legend  <- get_legend(fig_dummy6 + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure7  = plot_grid(plot_grid(title, figure7, ncol = 1, rel_heights = c(0.04,0.95)),
                     legend, nrow = 1, rel_widths = c(0.9,0.1))
ggsave("figures/figure7_paper.pdf", figure7, width = 18, height = 8)
```

```{r figure8, fig.height=14, fig.width=16}
p0       = ggplot() + geom_blank() + theme_cowplot() + theme(axis.line = element_blank())
figure8  = plot_grid(fig35,fig36,fig37,fig38, nrow = 2)
title    = ggdraw() + draw_label("Update Order of MR.ASH", fontface = 'bold', size = 20) 
legend  <- get_legend(fig_dummy7 + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure8  = plot_grid(plot_grid(title, figure8, ncol = 1, rel_heights = c(0.04,0.95)),
                     legend, nrow = 1, rel_widths = c(0.9,0.1))
ggsave("figures/figure8_paper.pdf", figure8, width = 18, height = 15)
```

```{r}
try(system("rm *.dat"))
try(system("rm analysis/*.dat"))
```