---
title: "Figures_for_the_paper"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(mr.ash.alpha); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
```

```{r fig1_1, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/sparsity500200.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 15)[,c(1:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df1_1    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Low-dimensional Setting", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.5", fontface  = 'bold', size = 14)
fig1_1    = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig1_2, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/sparsity50010000.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 15)[,c(1:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df1_2    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("High-dimensional Setting", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 10000, s = 1-10000, pve = 0.5", fontface  = 'bold', size = 14) 
fig1_2    = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig1_3, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/sparsityconst500200.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 14)[,c(1:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df1_3    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Sparse + Constant Signal", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointConst, n = 500, p = 200, s = 1-200, pve = 0.5", fontface  = 'bold', size = 14) 
fig1_3    = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig1_4, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/sparsecorr0.95dim500200.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 13)[,c(13,2:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df1_4    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Equicorrelated Design (rho = 0.95)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: EquicorrGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.5", fontface  = 'bold', size = 14) 
fig1_4    = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig1_5, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/sparsecorr0.955002000.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 13)[,c(13,2:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df1_5    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Equicorrelated Design (rho = 0.95)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: EquicorrGauss + PointNormal, n = 500, p = 2000, s = 1-2000, pve = 0.5", fontface  = 'bold', size = 14) 
fig1_5    = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig1_6, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/sparsepve0.9500200.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 13)[,c(13,2:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df1_6    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("High Proportion of Variance (PVE)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.9", fontface  = 'bold', size = 14) 
fig1_6    = plot_grid(suptitle, subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig1_7}
#df_tot = rbind(df1_1, df1_2, df1_3, df1_4, df1_5, df1_6)
#saveRDS(df_tot, "results/dataframe_for_box_1.RDS")
df_tot  = readRDS("results/dataframe_for_box_1.RDS")

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df_tot) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Boxplot summarizing Figure 1", fontface  = 'bold', size = 14) 
# subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.9", fontface  = 'bold', size = 14) 
fig1_7    = plot_grid(suptitle, fig_main, ncol = 1, rel_heights = c(0.06, 0.95))
ggsave("figures/box1_summary_for_paper.pdf", fig1_7, width = 9, height = 8)
```

```{r box1_for_paper, fig.height=20, fig.width=16}
figure1  = plot_grid(fig1_1,fig1_2,fig1_3,fig1_6,fig1_4,fig1_5, ncol = 2, rel_widths = c(0.5,0.5))
title    = ggdraw() + draw_label("Adaptation to Sparsity: Prediction Error (RMSE / sigma)", fontface = 'bold', size = 20)
figure1  = plot_grid(title, figure1, ncol = 1, rel_heights = c(0.05,0.95))
ggsave("figures/box1_for_paper.pdf", figure1, width = 18, height = 22)
```

```{r fig2_3, fig.height=11, fig.width=15}
res_df       = readRDS("results/signalshape500200200.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 14)[,c(1:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df2_3    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Varying Signal Shape (p = 200, s = 200)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + Spike-and-Slab, n = 500, p = 200, s = 200, pve = 0.5", fontface  = 'bold', size = 14) 
fig2_3    = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig2_4, fig.height=11, fig.width=15}
res_df       = readRDS("results/signalshape500200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 14)[,c(1:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df2_4    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Varying Signal Shape (p = 2000, s = 20)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + Spike-and-Slab, n = 500, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig2_4    = plot_grid(suptitle,subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig2_1, fig.height=11, fig.width=15}
res_df       = readRDS("results/pve50020020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 11)[,c(1:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df2_1    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Varying PVE (or SNR, Noise Variance)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0-0.9", fontface  = 'bold', size = 14) 
fig2_1    = plot_grid(suptitle, subtitle, fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig2_2, fig.height=11, fig.width=15}
res_df       = readRDS("results/pve500200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 11)[,c(1:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df2_2    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Varying PVE (or SNR, Noise Variance)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 2000, s = 20, pve = 0-0.9", fontface  = 'bold', size = 14) 
fig2_2    = plot_grid(suptitle, subtitle, fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r fig2_5, fig.height=11, fig.width=15}
res_df       = readRDS("results/largen200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")
#plr_list     = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 11)[,c(1:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
df2_5    = df
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Varying PVE (or SNR, Noise Variance)", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 2000, s = 20, pve = 0-0.9", fontface  = 'bold', size = 14) 
suptitle  = ggdraw() + draw_label("Varying n", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 200-5000, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig2_5    = plot_grid(suptitle, subtitle, fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
```

```{r}
#df_tot = rbind(df2_2, df2_3, df2_4, df2_5)
#saveRDS(df_tot,"results/dataframe_for_box2.RDS")
df_tot = readRDS("results/dataframe_for_box2.RDS")
col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df_tot) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Boxplot summarizing Figure 1", fontface  = 'bold', size = 14) 
# subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.9", fontface  = 'bold', size = 14) 
fig2_7    = plot_grid(suptitle, fig_main, ncol = 1, rel_heights = c(0.06, 0.95))
ggsave("figures/box2_summary_for_paper.pdf", fig2_7, width = 9, height = 8)
```

```{r figure2_for_paper, fig.height=20, fig.width=16}
figure2  = plot_grid(fig2_5, fig2_2, fig2_3, fig2_4, ncol = 2, rel_widths = c(0.5,0.5))
title    = ggdraw() + draw_label("Adaptation to p/n, Signal Shape, PVE: Prediction Error (RMSE / sigma)", fontface = 'bold', size = 20)
figure2  = plot_grid(title, figure2, ncol = 1, rel_heights = c(0.05,0.95))
ggsave("figures/box2_for_paper.pdf", figure2, width = 18, height = 15)
```

```{r figure3_for_paper}
res_df = list()
res_df[[1]] = readRDS("results/realgenotypesparsity1.RDS")
res_df[[2]] = readRDS("results/realgenotypesparsity5.RDS")
res_df[[3]] = readRDS("results/realgenotypesparsity20.RDS")
res_df[[4]] = readRDS("results/realgenotypesparsity100.RDS")
res_df[[5]] = readRDS("results/realgenotypesparsity500.RDS")
#saveRDS(res_df,"results/realgenotypeall.RDS")

method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")

df           = data.frame()
for (i in 1:length(res_df)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 13)[,c(13,2:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("RealGenotype", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: RealGenotype + PointNormal, n = 287, p = 4012-8760, s = 1-500, pve = 0.5", fontface  = 'bold', size = 14) 
fig3_1    = plot_grid(suptitle, subtitle, fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
ggsave("figures/box3_for_paper.pdf", fig3_1, width = 9, height = 8)
```

```{r fig4_1}
res_df       = readRDS("results/ecorr500200020.RDS")
res_df1      = readRDS("results/localcorr500200020.RDS")

method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn", "VarBVS","BayesB","Blasso","SuSiE", "Mr.ASH.opt")

df           = data.frame()
for (i in c(1,2,3,4,5,6)) {
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df[[i]]$pred, 20, 13)[,c(13,2:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
  
  df = rbind(df, data.frame(pred   = c(t(apply(matrix(res_df1[[i]]$pred, 20, 13)[,c(13,2:11)], 1, function(a) {a / min(a)}))),
                            fit    = rep(method_list, each = 20)))
}
df$fit   = factor(df$fit, levels = method_level)
#df       = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]

col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
fig_main = ggplot(df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.3)) + 
  theme_cowplot(font_size = 14) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
suptitle  = ggdraw() + draw_label("Real Genotype", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: RealGenotype + PointNormal, n = 287, p = 4012-8760, s = 1 - 500, pve = 0.5", fontface  = 'bold', size = 14) 
fig4_1    = plot_grid(suptitle, subtitle, fig_main, ncol = 1, rel_heights = c(0.04,0.04,0.95))
ggsave("figures/box4_for_paper.pdf", fig4_1, width = 9, height = 8)
```