```{r fig33, fig.height=11, fig.width=15}
res_df       = readRDS("results/initialization50020020.RDS")
res_df1      = readRDS("results/initialization500200020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:3
out = matrix(0,6,6)
for (i in 1:6) {
  out[i,] = c(colMeans(matrix(res_df[[a[i]]]$pred, 100, 3))[c(1,2,3)],
              colMeans(matrix(res_df1[[a[i]]]$pred, 100, 3))[c(1,2,3)])
}
col   = gg_color_hue(13)[c(1,5,3)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,5,3)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                p = factor(rep(c(200,2000), each = 6 * 3)),
                pred = c(out), fit = rep(c("null","scad","lasso","null","scad","lasso"), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("null","scad","lasso"))
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit, linetype = p)) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.25,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.12))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + Normal, n = 500, p = 200 or 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig33     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig34, fig.height=11, fig.width=15}
res_df       = readRDS("results/initialization50020020.RDS")
res_df1      = readRDS("results/initialization500200020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,6)
for (i in 1:6) {
  out[i,] = c(colMeans(matrix(res_df[[a[i]]]$vobj, 100, 3)[,1] - matrix(res_df[[a[i]]]$vobj, 100, 3))[c(1,2,3)],
              colMeans(matrix(res_df1[[a[i]]]$vobj, 100, 3)[,1] - matrix(res_df1[[a[i]]]$vobj, 100, 3))[c(1,2,3)])
}
ind   = 1:3
col   = gg_color_hue(13)[c(1,5,3)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,5,3)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                p = factor(rep(c(200,2000), each = length(rho_list) * 3)),
                vobj = c(out), fit = rep(c("null","scad","lasso","null","scad","lasso"), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("null","scad","lasso"))
fig_dummy6 = ggplot(df) + geom_line(aes(x = x, y = vobj, color = fit, linetype = p)) +
  geom_point(aes(x = x, y = vobj, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "variational objective difference (ELBO - ELBO_null)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape)
p1        = fig_dummy6 + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + Normal, n = 500, p = 200 or 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig34     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig35, fig.height=11, fig.width=15}
res_df       = readRDS("results/updateorder50020020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:7
out = matrix(0,6,7)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 100, 7))
}
colnames(out) = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                  "lasso.abs.order","random.permuted","true.abs.order")

col   = c(gg_color_hue(13)[1],"darkblue","dodgerblue","darkgreen","limegreen","orange","gold2")
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12,13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                                   "lasso.abs.order","random.permuted","true.abs.order")
)
fig_dummy7 = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit)) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.25,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.1))
p1        = fig_dummy7 + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig35     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig36, fig.height=11, fig.width=15}
res_df       = readRDS("results/updateorder500200020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:7
out = matrix(0,6,7)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 100, 7))
}
colnames(out) = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                  "lasso.abs.order","random.permuted","true.abs.order")

col   = c(gg_color_hue(13)[1],"darkblue","dodgerblue","darkgreen","limegreen","orange","gold2")
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12,13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                                   "lasso.abs.order","random.permuted","true.abs.order")
)
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit)) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.25,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.15))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig36     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig37, fig.height=11, fig.width=15}
res_df       = readRDS("results/updateorder50020020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:7
out = matrix(0,6,7)
for (i in 1:6) {
  out[i,] = -colMeans(matrix(res_df[[a[i]]]$vobj, 100, 7) - matrix(res_df[[a[i]]]$vobj, 100, 7)[,6])
}
colnames(out) = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                  "lasso.abs.order","random.permuted","true.abs.order")

col   = c(gg_color_hue(13)[1],"darkblue","dodgerblue","darkgreen","limegreen","orange","gold2")
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12,13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                vobj = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                                   "lasso.abs.order","random.permuted","true.abs.order")
)
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = vobj, color = fit)) +
  geom_point(aes(x = x, y = vobj, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "variational objective difference (ELBO - ELBO_null)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape)
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig37     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig38, fig.height=11, fig.width=15}
res_df       = readRDS("results/updateorder500200020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:7
out = matrix(0,6,7)
for (i in 1:6) {
  out[i,] = -colMeans(matrix(res_df[[a[i]]]$vobj, 100, 7) - matrix(res_df[[a[i]]]$vobj, 100, 7)[,6])
}
colnames(out) = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                  "lasso.abs.order","random.permuted","true.abs.order")

col   = c(gg_color_hue(13)[1],"darkblue","dodgerblue","darkgreen","limegreen","orange","gold2")
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12,13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                vobj = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("random.fixed","scad.path.order","lasso.path.order","univ.abs.order",
                                   "lasso.abs.order","random.permuted","true.abs.order")
)
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = vobj, color = fit)) +
  geom_point(aes(x = x, y = vobj, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "variational objective difference (ELBO - ELBO_null)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape)
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + PointNormal, n = 500, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig38     = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r figure3, fig.height=14, fig.width=16}
figure3_1 = plot_grid(fig33,fig34, nrow = 1)
title     = ggdraw() + draw_label("Initialization of MR.ASH", fontface = 'bold', size = 20) 
legend   <- get_legend(fig_dummy6 + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure3_1 = plot_grid(plot_grid(title, figure3_1, ncol = 1, rel_heights = c(0.04,0.95)),
                     legend, nrow = 1, rel_widths = c(0.9,0.1))
figure3_2 = plot_grid(fig35,fig37,fig36,fig38, nrow = 2)
title     = ggdraw() + draw_label("Update Order of MR.ASH", fontface = 'bold', size = 20) 
legend   <- get_legend(fig_dummy7 + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure3_2 = plot_grid(plot_grid(title, figure3_2, ncol = 1, rel_heights = c(0.04,0.95)),
                     legend, nrow = 1, rel_widths = c(0.9,0.1))
figure3   = plot_grid(figure3_1, figure3_2, ncol = 1, rel_heights = c(0.3,0.6))
ggsave("figures/figure3_for_paper.pdf", figure3, width = 18, height = 22)
```

```{r fig4_1, fig.height=11, fig.width=15}
res_df       = readRDS("results/ecorr50020020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn",
                 "Mr.ASH.order","Mr.ASH.init")
method_level = c("Mr.ASH","Mr.ASH.order","Mr.ASH.init","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[c(1,12,13,2:11)]
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,13)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 20, 13))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn",
                  "Mr.ASH.order",
                  "Mr.ASH.init")
ind = c(1,6:13)
out = out[,ind]

col   = gg_color_hue(13)[c(1:7,12:13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12:13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2",
                                    "VarBVS","BayesB","Blasso","SuSiE",
                                    "Mr.ASH.order",
                                    "Mr.ASH.init"))
df$size = 0.5
df$size[1:length(rho_list)] = 1.2
df$lt = "solid"
df$lt[43:48] = "dashed"
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit), size = df$size, linetype = df$lt) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.2))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
suptitle  = ggdraw() + draw_label("Varying Correlation", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: EquicorrGauss + PointNormal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig4_1    = plot_grid(subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.95))
```

```{r fig4_2, fig.height=11, fig.width=15}
res_df       = readRDS("results/ecorr500200020.RDS")
method_list  = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn",
                 "Mr.ASH.order","Mr.ASH.init")
method_level = c("Mr.ASH","Mr.ASH.order","Mr.ASH.init","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "VarBVS","BayesB","Blasso","SuSiE")
col          = gg_color_hue(13)[c(1,12,13,2:11)]
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,13)
for (i in 1:6) {
  out[i,] = colMeans(matrix(res_df[[a[i]]]$pred, 20, 13))
}
colnames(out) = c("Mr.ASH","VarBVS","BayesB","Blasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn",
                  "Mr.ASH.order",
                  "Mr.ASH.init")
ind = c(1,6:13)
out = out[,ind]

col   = gg_color_hue(13)[c(1:7,12:13)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:7,12:13)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                pred = c(out), fit = rep(colnames(out), each = length(rho_list)))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn","E-NET2","Lasso2","Ridge2",
                                    "VarBVS","BayesB","Blasso","SuSiE",
                                    "Mr.ASH.order",
                                    "Mr.ASH.init"))
df$size = 0.5
df$size[1:length(rho_list)] = 1.2
df$lt = "solid"
df$lt[43:48] = "dashed"
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit), size = df$size, linetype = df$lt) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.2))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
suptitle  = ggdraw() + draw_label("Varying Correlation", fontface  = 'bold', size = 14) 
subtitle  = ggdraw() + draw_label("Scenario: EquicorrGauss + PointNormal, n = 500, p = 2000, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig4_2    = plot_grid(subtitle,fig_main, ncol = 1, rel_heights = c(0.04,0.95))
```

```{r figure4, fig.height=20, fig.width=16}
figure4  = plot_grid(fig4_1, fig4_2, ncol = 2, rel_widths = c(0.5,0.5))
title    = ggdraw() + draw_label("Varying Correlation: Prediction Error (RMSE / sigma)", fontface = 'bold', size = 20)
legend <- get_legend(fig_dummy + theme(legend.box.margin = margin(0, 0, 0, 12)))
figure4  = plot_grid(plot_grid(title, figure4, ncol = 1, rel_heights = c(0.05,0.95)), legend, nrow = 1, rel_widths = c(0.9,0.1))
ggsave("figures/figure4_for_paper.pdf", figure4, width = 18, height = 8)
```