---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r code, message = FALSE, warning = FALSE, eval= FALSE}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(mr.ash); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
fit.mr.ash = function(X, y, X.test, y.test, seed = 1, sa2 = (2^((0:19)/5) - 1)^2, method = "caisa",
                      convtol = 1e-8) {
  
  # set seed
  set.seed(seed)
  
  # run mr.ash
  t.mr.ash           = system.time(
    fit.mr.ash        <- mr.ash(X = X, y = y, sa2 = sa2, method = method,
                                max.iter = 100,
                                standardize = standardize,
                                tol = list(epstol = 1e-12, convtol = convtol)))
  
  return (list(fit = fit.mr.ash, t = t.mr.ash[3],
               rsse = norm(y.test - predict(fit.mr.ash, X.test), '2')))
}
tdat1        = list()
method_num   = 3
iter_num     = 20
pred         = matrix(0, iter_num, method_num)
time         = matrix(0, iter_num, method_num)
vobj         = matrix(0, iter_num, method_num)
numiter      = matrix(0, iter_num, method_num)
colnames(pred) <- colnames(time) <- colnames(vobj) <- colnames(numiter) <-
  c("mr.ash.original","mr.ash.block", "mr.ash.modular")

for (i in 1:2) {
  data          = simulate_data(n = 100, p = 10000, s = 10, seed = i, signal = "normal",
                                design = "equicorrgauss", pve = 0.99, rho = 0.1)
 
  fit1        = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                           sa2 = (2^((0:19) / 5) - 1)^2)
  fit2        = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                           sa2 = (2^((0:19) / 5) - 1)^2, method = "update_g")
  for (j in 1:2) {
    fit           = get(paste("fit",j,sep = ""))
    pred[i,j]     = fit$rsse / sqrt(500) / data$sigma
    numiter[i,j]  = fit$fit$iter
    vobj[i,j]     = fit$fit$varobj[fit$fit$iter]
    time[i,j]     = fit$t
  }
  
  print(c(pred[i,]))
  print(c(vobj[i,]))
}
plot(fit1$fit$varobj, type = "l"); lines(fit2$fit$varobj, col = 2); lines(fit3$fit$varobj, col = 3)
```