---
title: "Result16"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r package, message = FALSE, warning = FALSE}
setwd("../mr-ash-workflow")
library(Matrix); library(ggplot2); library(cowplot); library(mr.ash.alpha); library(varbvs)
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
```

```{r code, eval = FALSE, message = FALSE, warning = FALSE}
n      = 100
p      = 2000
s      = 20
sa2    = (2^((0:19)/2) - 1)^2
K      = length(sa2)
time   = matrix(0,20,5)
sig    = matrix(0,20,6)
pred   = matrix(0,20,5)
tdat   = list()
vdat   = list()
pve    = 0.9999
maxiter = 2000
miniter = 1
vobj    = list(matrix(0,20,maxiter), matrix(0,20,maxiter), matrix(0,20,maxiter),
               matrix(0,20,maxiter), matrix(0,20,maxiter))

for (i in 1:20) {
  data          = simulate_data(n, p, s = s, seed = i, signal = "normal",
                                design = "indepgauss", pve = pve)
  
  sigma.init = var(data$y)
  #sigma.init = data$sigma^2
  
  t.mr.ash1           = system.time(
    fit.mr.ash1        <- mr.ash(X = data$X, y = data$y, sa2 = sa2, sigma2 = sigma.init,
                                max.iter = maxiter, min.iter = miniter,
                                standardize = standardize,
                                tol = list(epstol = 1e-12, convtol = 1e-8)))
  print(c(fit.mr.ash1$pi))
  
  t.mr.ash2           = system.time(
    fit.mr.ash2        <- mr.ash(X = data$X, y = data$y, sa2 = sa2, method = "sigma_scaled",
                                max.iter = maxiter, min.iter = miniter, sigma2 = sigma.init,
                                standardize = standardize,
                                tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  t.mr.ash3           = system.time(
    fit.mr.ash3        <- mr.ash(X = data$X, y = data$y, sa2 = sa2 * data$sigma^2, method = "sigma_indep",
                                max.iter = maxiter, min.iter = miniter, sigma2 = sigma.init,
                                standardize = standardize,
                                tol = list(epstol = 1e-12, convtol = 1e-8)))
  t.mr.ash4           = system.time(
    fit.mr.ash4        <- mr.ash(X = data$X, y = data$y, sa2 = sa2, method = "update_g",
                                max.iter = maxiter, min.iter = miniter, sigma2 = sigma.init,
                                standardize = standardize,
                                tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  t.mr.ash5           = system.time({
    fit.mr.ash5        <- varbvsmix(X = data$X, Z = NULL, y = data$y, sa = sa2,
                                    mu = matrix(0, p, K), sigma = sigma.init, maxiter = maxiter,
                                    alpha = matrix(1, p, K) / K, update.sa = FALSE,
                                    update.sigma = TRUE, verbose = FALSE)
  fit.mr.ash5$beta    = rowSums(fit.mr.ash5$alpha * fit.mr.ash5$mu)})
  fit.mr.ash5$intercept = fit.mr.ash5$mu.cov
  fit.mr.ash5$varobj  = -fit.mr.ash5$logZ - log(n)/2
  fit.mr.ash5$iter    = length(fit.mr.ash5$logZ)
  
  for (j in 1:5) {
    fit               = get(paste("fit.mr.ash", j, sep = ""))
    pred[i,j]         = norm(data$y.test - data$X.test %*% fit$beta - fit$intercept, '2') / sqrt(n) / data$sigma
    vobj[[j]][i,1:fit$iter] = fit$varobj
    time[i,j]         = get(paste("t.mr.ash", j, sep = ""))[3]
    sig[i,j]          = fit$sigma
  }
  sig[i,6]            = data$sigma^2
  
  print(c(pred[i,]), digits = 3)
  print(c(sig[i,]), digits = 3)
  
}
tdat[[1]] = data.frame(pred = c(pred), time = c(time), sigma = c(sig[,1:5]), sigma_true = sig[,6],
                       fit  = rep(c("sig_dep_g","sig_scaled_beta","sig_indep_g","update_g","varbvsmix"), each = 20))
vdat[[1]] = vobj
```

```{r code2, eval = FALSE, message = FALSE, warning = FALSE}
n      = 500
p      = 2000
s      = 20
sa2    = (2^((0:19)/20) - 1)^2
pve    = 0.5
for (i in 1:20) {
  data          = simulate_data(n, p, s = s, seed = i, signal = "normal",
                                design = "indepgauss", pve = pve)
  
  sigma.init = var(data$y)
  #sigma.init = data$sigma^2
  
  t.mr.ash1           = system.time(
    fit.mr.ash1        <- mr.ash(X = data$X, y = data$y, sa2 = sa2, sigma2 = sigma.init,
                                max.iter = maxiter, min.iter = miniter,
                                standardize = standardize,
                                tol = list(epstol = 1e-12, convtol = 1e-8)))
  print(c(fit.mr.ash1$pi))
  
  t.mr.ash2           = system.time(
    fit.mr.ash2        <- mr.ash(X = data$X, y = data$y, sa2 = sa2, method = "sigma_scaled",
                                max.iter = maxiter, min.iter = miniter, sigma2 = sigma.init,
                                standardize = standardize,
                                tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  t.mr.ash3           = system.time(
    fit.mr.ash3        <- mr.ash(X = data$X, y = data$y, sa2 = sa2 * data$sigma^2, method = "sigma_indep",
                                max.iter = maxiter, min.iter = miniter, sigma2 = sigma.init,
                                standardize = standardize,
                                tol = list(epstol = 1e-12, convtol = 1e-8)))
  t.mr.ash4           = system.time(
    fit.mr.ash4        <- mr.ash(X = data$X, y = data$y, sa2 = sa2, method = "update_g",
                                max.iter = maxiter, min.iter = miniter, sigma2 = sigma.init,
                                standardize = standardize,
                                tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  t.mr.ash5           = system.time({
    fit.mr.ash5        <- varbvsmix(X = data$X, Z = NULL, y = data$y, sa = sa2,
                                    mu = matrix(0, p, K), sigma = sigma.init, maxiter = maxiter,
                                    alpha = matrix(1, p, K) / K, update.sa = FALSE, tol = 1e-8,
                                    update.sigma = TRUE, verbose = FALSE)
  fit.mr.ash5$beta    = rowSums(fit.mr.ash5$alpha * fit.mr.ash5$mu)})
  fit.mr.ash5$intercept = fit.mr.ash5$mu.cov
  fit.mr.ash5$varobj  = -fit.mr.ash5$logZ - log(n)/2
  fit.mr.ash5$iter    = length(fit.mr.ash5$logZ)
  
  for (j in 1:5) {
    fit               = get(paste("fit.mr.ash", j, sep = ""))
    pred[i,j]         = norm(data$y.test - data$X.test %*% fit$beta - fit$intercept, '2') / sqrt(n) / data$sigma
    vobj[[j]][i,1:fit$iter] = fit$varobj
    time[i,j]         = get(paste("t.mr.ash", j, sep = ""))[3]
    sig[i,j]          = fit$sigma
  }
  sig[i,6]            = data$sigma^2
  
  print(c(pred[i,]), digits = 3)
  print(c(sig[i,]), digits = 3)
  
}
tdat[[2]] = data.frame(pred = c(pred), time = c(time), sigma = c(sig[,1:5]), sigma_true = sig[,6],
                       fit  = rep(c("sig_dep_g","sig_scaled_beta","sig_indep_g","update_g","varbvsmix"), each = 20))
vdat[[2]] = vobj
```

```{r}
tdat[[1]]$rate = tdat[[1]]$sigma / tdat[[1]]$sigma_true
tdat[[2]]$rate = tdat[[2]]$sigma / tdat[[2]]$sigma_true
p1 = my.box(tdat[[1]], "fit", "rate") + coord_cartesian(ylim = c(0.1,40)) +
  scale_y_continuous(trans = "log10") + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  labs(y = "sigma2_est / sigma2_true", title = "n = 100, p = 2000, pve = 0.9999")
p2 = my.box(tdat[[2]], "fit", "rate") + coord_cartesian(ylim = c(0.9,1.3)) +
  scale_y_continuous(trans = "log10", breaks = c(0.9,1,1.1,1.2,1.3)) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  labs(y = "sigma2_est / sigma2_true", title = "n = 500, p = 2000, pve = 0.5")
plot_grid(p1, p2)
```

```{r}
p1 = my.box(tdat[[1]], "fit", "time") + coord_cartesian(ylim = c(0.1,20)) +
  scale_y_continuous(trans = "log10", breaks = c(0.1,0.3,1,3,10)) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  labs(y = "computation time (sec)", title = "n = 100, p = 2000, pve = 0.9999")
p2 = my.box(tdat[[2]], "fit", "time") + coord_cartesian(ylim = c(1,20)) +
  scale_y_continuous(trans = "log10", breaks = c(1,3,10,30)) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  labs(y = "computation time (sec)", title = "n = 500, p = 2000, pve = 0.5")
plot_grid(p1, p2)
```

```{r}
p1 = my.box(tdat[[1]], "fit", "pred") + coord_cartesian(ylim = c(1,2)) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.5,2)) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  labs(y = "RMSE / sigma", title = "n = 100, p = 2000, pve = 0.9999")
p2 = my.box(tdat[[2]], "fit", "pred") + coord_cartesian(ylim = c(1,1.12)) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1)) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  labs(y = "RMSE / sigma", title = "n = 500, p = 2000, pve = 0.5")
plot_grid(p1, p2)
```