---
title: "Result12_Initialization"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

### PVE

We fix PVE = 0.5.

### Packages / Libraries

A list of packages we have loaded is collapsed. Please click "code" to see the list.

```{r library, message = FALSE}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(varbvs2); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
```

## Results 

```{r fig1, fig.height=20, fig.width=15}
res_df       = readRDS("../results/initialization50020020.RDS")
res_df1      = readRDS("../results/initialization500200020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
ind          = 1:3
out = matrix(0,6,6)
for (i in 1:6) {
  out[i,] = c(colMeans(matrix(res_df[[a[i]]]$pred, 100, 3))[c(1,2,3)],
              colMeans(matrix(res_df1[[a[i]]]$pred, 100, 3))[c(1,2,3)])
}
col   = gg_color_hue(13)[c(1,5,3)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,5,3)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                p = factor(rep(c(200,2000), each = 6 * 3)),
                pred = c(out), fit = rep(c("null","scad","lasso","null","scad","lasso"), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("null","scad","lasso"))
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = pred, color = fit, linetype = p)) +
  geom_point(aes(x = x, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.05,1.1,1.15,1.2,1.25,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.12))
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + Normal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig1.1      = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

```{r fig2, fig.height=20, fig.width=15}
res_df       = readRDS("../results/initialization50020020.RDS")
res_df1      = readRDS("../results/initialization500200020.RDS")
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)
a            = c(1,2,3,4,5,6)
out = matrix(0,6,6)
for (i in 1:6) {
  out[i,] = c(colMeans(matrix(res_df[[a[i]]]$vobj, 100, 3)[,1] - matrix(res_df[[a[i]]]$vobj, 100, 3))[c(1,2,3)],
              colMeans(matrix(res_df1[[a[i]]]$vobj, 100, 3)[,1] - matrix(res_df1[[a[i]]]$vobj, 100, 3))[c(1,2,3)])
}
ind   = 1:3
col   = gg_color_hue(13)[c(1,3,5)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1,3,5)]
df = data.frame(x = rep(1:length(rho_list),length(ind)), rho = rep(rho_list, length(ind)),
                p = factor(rep(c(200,2000), each = length(rho_list) * 3)),
                vobj = c(out), fit = rep(c("null","scad","lasso","null","scad","lasso"), each = length(rho_list)))
df$fit = factor(df$fit, levels = c("null","scad","lasso"))
fig_dummy = ggplot(df) + geom_line(aes(x = x, y = vobj, color = fit, linetype = p)) +
  geom_point(aes(x = x, y = vobj, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6),
                     labels = c("0","0.3","0.6","0.9","0.95","0.99")) +
  labs(y = "predictior error (rmse / sigma)", x = "correlation across columns of X (rho)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape)
p1        = fig_dummy + theme(legend.position = "none")
fig_main  = p1
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + Normal, n = 500, p = 200, s = 20, pve = 0.5", fontface  = 'bold', size = 14) 
fig1.2      = plot_grid(subtitle,p1, ncol = 1, rel_heights = c(0.05,0.95))
```

## Source Code

```{r code, eval = FALSE}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(mr.ash.alpha); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')

tdat1        = list()
n            = 500
p            = 2000
s            = 20
sa2          = (2^((0:19) / 5) - 1)^2
method_list  = c("null","scad","lasso")
method_num   = length(method_list)
iter_num     = 100
pred         = matrix(0, iter_num, method_num); colnames(pred) = method_list
time         = matrix(0, iter_num, method_num); colnames(time) = method_list
numiter      = matrix(0, iter_num, method_num); colnames(numiter) = method_list
vobj         = matrix(0, iter_num, method_num); colnames(vobj) = method_list
rho_list     = c(0,0.3,0.6,0.9,0.95,0.99)

for (iter in 1:6) {
  rho           = rho_list[iter]
for (i in 1:iter_num) {
  data          = simulate_data(n, p, s = s, seed = i, signal = "normal", rho = rho,
                                design = "equicorrgauss", pve = 0.5)
  X             = data$X
  y             = data$y
  
  fit1             <- fit.lasso(data$X, data$y, data$X.test, data$y.test, seed = i)
  fit2             <- fit.scad2(data$X, data$y, data$X.test, data$y.test, seed = i)
  lasso.beta       = as.vector(coef(fit1$fit))[-1]
  lasso.time       = c(fit1$t, fit1$t2)
  scad.beta        = as.vector(coef(fit2$fit))[-1]
  scad.time        = c(fit2$t, fit2$t2)
  
  t.mrash1          = system.time(
    fit.mrash1       <- mr.ash(X = X, y = y, sa2 = sa2,
                               max.iter = 2000,
                               standardize = standardize,
                               tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  t.mrash2          = system.time(
    fit.mrash2       <- mr.ash(X = X, y = y, sa2 = sa2,
                               max.iter = 2000, beta.init = scad.beta,
                               standardize = standardize,
                               tol = list(epstol = 1e-12, convtol = 1e-8)))
  t.mrash3          = system.time(
    fit.mrash3       <- mr.ash(X = X, y = y, sa2 = sa2,
                               max.iter = 2000, beta.init = lasso.beta,
                               standardize = standardize,
                               tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  for (j in 1:3) {
    fit           = get(paste("fit.mrash",j,sep = ""))
    pred[i,j]     = norm(data$y.test - predict(fit, data$X.test), '2') / sqrt(500) / data$sigma
    numiter[i,j]  = fit$iter
    vobj[i,j]     = fit$varobj[fit$iter]
    time[i,j]     = get(paste("t.mrash",j,sep = ""))[3]
  }
  
  print(c(vobj[i,]))
}
tdat1[[iter]] = data.frame(pred = c(pred), vobj = c(vobj), time = c(time),
                           numiter = c(numiter),
                           order = rep(method_list, each = iter_num))
}
```
