---
  title: "Figure3_Sourcecode1"
  output:
    workflowr::wflow_html:
    code_folding: hide
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Source Code

```{r library, message = FALSE}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(mr.ash.alpha); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
```

## Scenarios

### Scenario 7

Scenario 7 (Varying $n$): $n \in [\textrm{200}, \textrm{5,000}]$, $p = \textrm{2,000}$, $s = \textrm{20}$, $\textrm{Design} = \textrm{IndepGauss}$, $\textrm{PVE} = 0.5$ and $\textrm{SignalShape} = \textrm{PointNormal}$.

```{r code7, eval = TRUE}
tdat7        = list()
n_range      = c(200,500,1000,2000,5000)
p            = 2000
s            = 20
method_list  = c("varbvs","bayesb","blasso","susie","enet","lasso","ridge","scad2","mcp2","l0learn")
method_list2 = c("mr.ash", method_list)
method_num   = length(method_list2)
iter_num     = 20
pred         = matrix(0, iter_num, method_num); colnames(pred) = method_list2
time         = matrix(0, iter_num, method_num); colnames(time) = method_list2

for (iter in 1:5) {
  n               = n_range[iter]
for (i in 1:20) {
  
  data          = simulate_data(n, p, s = s, seed = i, signal = "normal", pve = 0.5)
  
  for (j in 1:length(method_list)) {
    fit.method    = get(paste("fit.",method_list[j],sep = ""))
    fit           = fit.method(data$X, data$y, data$X.test, data$y.test, seed = i)
    pred[i,j+1]   = fit$rsse / data$sigma / sqrt(n)
    time[i,j+1]   = fit$t
    
    if (method_list[j] == "lasso") {
      pred[i,method_num - 1] = fit$rsse2 / data$sigma / sqrt(n)
    } else if (method_list[j] == "enet") {
      pred[i,method_num - 2] = fit$rsse2 / data$sigma / sqrt(n)
    } else if (method_list[j] == "ridge") {
      pred[i,method_num - 0] = fit$rsse2 / data$sigma / sqrt(n)
    }
  }
 
  fit         = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                           sa2 = (2^((0:19) / 20) - 1)^2)
  pred[i,1]   = fit$rsse / data$sigma / sqrt(n)
  time[i,1]   = fit$t
  
  print(c(time[i,]), digits = 4)
  print(c(pred[i,]), digits = 4)
}
  print("-----------------------------------")
  tdat7[[iter]] = data.frame(pred = c(pred), time = c(time), fit = rep(method_list2, each = 20))
}
```

## Save the results

```{r remove}
try(system("rm *.dat"))
try(system("rm ../*.dat"))
try(system("rm analysis/*.dat"))
try(system("rm ../analysis/*.dat"))
```

```{r saveresults}
saveRDS(tdat7, "results/scenario7.RDS")
```
