---
title: "Figure8_Sourcecode"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Source Code

```{r library, message = FALSE}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(mr.ash.alpha); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
```

## Scenarios

```{r code11, eval = TRUE}
tdat11       = list()
n            = 500
p            = 2000
s            = 20
rho_range    = c(0.99,0.95,0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1,0)
method_list  = c("lasso")
method_list2 = c("mr.ash.vanilla", method_list, "mr.ash.order", "mr.ash.init","mr.ash.both")
method_num   = length(method_list2)
iter_num     = 100
pred         = matrix(0, iter_num, method_num); colnames(pred) = method_list2
time         = matrix(0, iter_num, method_num); colnames(time) = method_list2


for (iter in 1:12) {
  rho             = rho_range[iter]
  
  for (i in 1:100) {
    data          = simulate_data(n, p, s = s, seed = i, signal = "normal", pve = 0.5,
                                  design = "equicorrgauss", rho = rho)
    
    for (j in 1:length(method_list)) {
      fit.method    = get(paste("fit.",method_list[j],sep = ""))
      suppressWarnings(
      fit          <- fit.method(data$X, data$y, data$X.test, data$y.test, seed = i))
      pred[i,j+1]   = fit$rsse / data$sigma / sqrt(n)
      time[i,j+1]   = fit$t
      
      if (method_list[j] == "lasso") {
        lasso.path.order = mr.ash.alpha:::path.order(fit$fit$glmnet.fit)
        lasso.beta       = as.vector(coef(fit$fit))[-1]
        lasso.time       = c(fit$t, fit$t2)
      }
    }
    
    fit         = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                             sa2 = (2^((0:19) / 5) - 1)^2)
    pred[i,1]   = fit$rsse / data$sigma / sqrt(n)
    time[i,1]   = fit$t
    
    fit         = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                              update.order = lasso.path.order,
                             sa2 = (2^((0:19) / 5) - 1)^2)
    pred[i,j+2] = fit$rsse / data$sigma / sqrt(n)
    time[i,j+2] = fit$t + lasso.time[2]
    
    fit         = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                              beta.init = lasso.beta,
                             sa2 = (2^((0:19) / 5) - 1)^2)
    pred[i,j+3] = fit$rsse / data$sigma / sqrt(n)
    time[i,j+3] = fit$t + lasso.time[1]
    
    fit         = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                              beta.init = lasso.beta, update.order = lasso.path.order,
                             sa2 = (2^((0:19) / 5) - 1)^2)
    pred[i,j+4] = fit$rsse / data$sigma / sqrt(n)
    time[i,j+4] = fit$t + lasso.time[2]
    
    print(c(pred[i,]), digits = 3)
  }
  tdat11[[iter]] = data.frame(pred = c(pred), time = c(time), fit = rep(method_list2, each = 100))
}
```

### Scenario 12

```{r code12, eval = TRUE}
tdat12       = list()
n            = 500
p            = 200
s            = 20
rho_range    = c(0.99,0.95,0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1,0)
method_list  = c("lasso")
method_list2 = c("mr.ash.vanilla", method_list, "mr.ash.order", "mr.ash.init","mr.ash.both")
method_num   = length(method_list2)
iter_num     = 100
pred         = matrix(0, iter_num, method_num); colnames(pred) = method_list2
time         = matrix(0, iter_num, method_num); colnames(time) = method_list2


for (iter in 1:12) {
  rho             = rho_range[iter]
  
  for (i in 1:100) {
    data          = simulate_data(n, p, s = s, seed = i, signal = "normal", pve = 0.5,
                                  design = "equicorrgauss", rho = rho)
    
    for (j in 1:length(method_list)) {
      fit.method    = get(paste("fit.",method_list[j],sep = ""))
      suppressWarnings(
      fit          <- fit.method(data$X, data$y, data$X.test, data$y.test, seed = i))
      pred[i,j+1]   = fit$rsse / data$sigma / sqrt(n)
      time[i,j+1]   = fit$t
      
      if (method_list[j] == "lasso") {
        lasso.path.order = mr.ash.alpha:::path.order(fit$fit$glmnet.fit)
        lasso.beta       = as.vector(coef(fit$fit))[-1]
        lasso.time       = c(fit$t, fit$t2)
      }
    }
    
    fit         = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                             sa2 = (2^((0:19) / 5) - 1)^2)
    pred[i,1]   = fit$rsse / data$sigma / sqrt(n)
    time[i,1]   = fit$t
    
    fit         = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                              update.order = lasso.path.order,
                             sa2 = (2^((0:19) / 5) - 1)^2)
    pred[i,j+2] = fit$rsse / data$sigma / sqrt(n)
    time[i,j+2] = fit$t + lasso.time[2]
    
    fit         = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                              beta.init = lasso.beta,
                             sa2 = (2^((0:19) / 5) - 1)^2)
    pred[i,j+3] = fit$rsse / data$sigma / sqrt(n)
    time[i,j+3] = fit$t + lasso.time[1]
    
    fit         = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                              beta.init = lasso.beta, update.order = lasso.path.order,
                             sa2 = (2^((0:19) / 5) - 1)^2)
    pred[i,j+4] = fit$rsse / data$sigma / sqrt(n)
    time[i,j+4] = fit$t + lasso.time[2]
    
    print(c(pred[i,]), digits = 3)
  }
  tdat12[[iter]] = data.frame(pred = c(pred), time = c(time), fit = rep(method_list2, each = 100))
}
```

## Save the results

```{r remove}
try(system("rm *.dat"))
try(system("rm ../*.dat"))
try(system("rm analysis/*.dat"))
try(system("rm ../analysis/*.dat"))
```

```{r saveresults}
saveRDS(tdat12, "results/scenario12.RDS")
saveRDS(tdat13, "results/scenario13.RDS")
```