---
title: "Figure10_for_the_paper"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(ggplot2); library(cowplot);
## function for color
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
```

## Figure

### Scenario 3-2

```{r fig10_1, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/scenario3-2.RDS")
s_range = c(1,5,20,100,500,2000)
a = length(s_range)
out = matrix(0,a,13)
lower = matrix(0,a,13)
upper = matrix(0,a,13)
for (i in 1:a) {
  out[i,] = apply(matrix(res_df[[i]]$pred, 20, 13), 2, mean)
  lower[i,] = apply(matrix(res_df[[i]]$pred, 20, 13), 2, function(x) quantile(x, probs = 0.1))
  upper[i,] = apply(matrix(res_df[[i]]$pred, 20, 13), 2, function(x) quantile(x, probs = 0.9))
}
colnames(out) = c("Mr.ASH","varbvs","BayesB","B-Lasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn","Mr.ASH.order","Mr.ASH2")
ind = 1:13
out = out[,ind]
lower = lower[,ind]
upper = upper[,ind]
col   = gg_color_hue(13)[c(1:8,11)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:8,11)]
df = data.frame(s = rep(s_range, length(ind)), pred = c(out), fit = rep(colnames(out), each = a),
                lower = c(lower), upper = c(upper))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn",
                                    "varbvs","BayesB","B-Lasso","SuSiE","Mr.ASH.order","Mr.ASH.vanilla"))
df$size = 0.5
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]
#df = df[df$fit %in% c("Mr.ASH","varbvs","BayesB","B-Lasso","SuSiE"),]
df$size[1:5] = 1.2
fig_dummy10 = ggplot(df) + geom_line(aes(x = s, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = s, y = pred, color = fit, shape = fit), size = 3) +
  theme_cowplot(font_size = 22) +
  scale_x_continuous(trans = "log10", breaks = unique(df$s)) +
  labs(y = "predictior error (rmse / sigma)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 0,hjust = 1),
        axis.title.y = element_blank(), axis.title.x = element_blank()) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4)) +
  coord_cartesian(ylim = c(1,1.45))
fig_main = fig_dummy10 + theme(legend.position = "none")
subtitle  = ggdraw() + draw_label("Point-const-signal", fontface  = 'bold', size = 22)  
fig10_1    = plot_grid(subtitle, fig_main, ncol = 1, rel_heights = c(0.08,0.92))
```

### Scenario 4-2

```{r fig10_2, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/scenario4-2.RDS")
s_range = c(1,5,20,100,500,2000)
a = length(s_range)
out = matrix(0,a,13)
lower = matrix(0,a,13)
upper = matrix(0,a,13)
for (i in 1:a) {
  out[i,] = apply(matrix(res_df[[i]]$pred, 20, 13), 2, mean)
  lower[i,] = apply(matrix(res_df[[i]]$pred, 20, 13), 2, function(x) quantile(x, probs = 0.1))
  upper[i,] = apply(matrix(res_df[[i]]$pred, 20, 13), 2, function(x) quantile(x, probs = 0.9))
}
colnames(out) = c("Mr.ASH","varbvs","BayesB","B-Lasso","SuSiE","E-NET","Lasso","Ridge",
                  "SCAD","MCP","L0Learn","Mr.ASH.order","Mr.ASH2")
ind = 1:13
out = out[,ind]
lower = lower[,ind]
upper = upper[,ind]
col   = gg_color_hue(13)[c(1:8,11)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[c(1:8,11)]
df = data.frame(s = rep(s_range, length(ind)), pred = c(out), fit = rep(colnames(out), each = a),
                lower = c(lower), upper = c(upper))
df$fit = factor(df$fit, levels =  c("Mr.ASH","E-NET","Lasso","Ridge",
                                    "SCAD","MCP","L0Learn",
                                    "varbvs","BayesB","B-Lasso","SuSiE","Mr.ASH.order","Mr.ASH.vanilla"))
df$size = 0.5
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]
#df = df[df$fit %in% c("Mr.ASH","varbvs","BayesB","B-Lasso","SuSiE"),]
df$size[1:5] = 1.2
p1 = ggplot(df) + geom_line(aes(x = s, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = s, y = pred, color = fit, shape = fit), size = 3) +
  theme_cowplot(font_size = 22) +
  scale_x_continuous(trans = "log10", breaks = unique(df$s)) +
  labs(y = "predictior error (rmse / sigma)", x = "number of nonzero coefficients (s)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 0,hjust = 1),
        axis.title.y = element_blank(), axis.title.x = element_blank(),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,2,5,10)) +
  coord_cartesian(ylim = c(1,10))
fig_main = p1
subtitle  = ggdraw() + draw_label("Strong-signal", fontface  = 'bold', size = 22)  
fig10_2    = plot_grid(subtitle, fig_main, ncol = 1, rel_heights = c(0.08,0.92))
```

### Scenario 9-2

```{r fig10_3, fig.height=11, fig.width=15, fig.align = "center"}
res_df = readRDS("results/scenario9-2.RDS")
method_list  = c("Mr.ASH","varbvs","BayesB","B-Lasso","SuSiE","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn")
method_level = c("Mr.ASH","E-NET","Lasso","Ridge",
                 "SCAD","MCP","L0Learn",
                 "varbvs","BayesB","B-Lasso","SuSiE")
x_range      = 2^(c(1,2,3,4,5,6,7,8) - 1)
df           = data.frame()
for (i in 1:8) {
  res_df[[i]]       = res_df[[i]][1:220,]
  res_df[[i]]$fit   = rep(method_list, each = 20)
  res_df[[i]]$fit   = factor(res_df[[i]]$fit, levels = method_level)
  df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 11))),
                                           df   = x_range[i],
                                           fit  = method_list))
}
df = df[df$fit %in% c("Mr.ASH","E-NET","Lasso","Ridge","SCAD","MCP","L0Learn"),]
#df = df[df$fit %in% c("Mr.ASH","varbvs","BayesB","B-Lasso","SuSiE"),]
df$fit = factor(df$fit, levels = method_level)
df$size = 0.5
df$size[1:8] = 1.2
col   = gg_color_hue(13)[1:7]
shape = c(19,17,24,25,9,3,11,4,5,7,8,1)[1:7]
p1    = ggplot(df) + geom_line(aes(x = df, y = pred, color = fit), size = df$size) +
  geom_point(aes(x = df, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 22) +
  scale_x_continuous(trans = "log10", breaks = c(1,2,4,8,16,32,64,128),
                     labels = c("t (df=1)","t (df=2)","t (df=4)","t (df=8)","Laplace",
                                "Normal","Uniform","Constant")) +
  labs(y = "predictior error (rmse / sigma)", x = "signal shape (distribution of nonzero coefficients)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        axis.title.y = element_blank(),
        legend.position = "none") +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3,1.4,1.5)) +
  coord_cartesian(ylim = c(1,1.5))
fig_main  = p1
subtitle  = ggdraw() + draw_label("Signal-shape-dense", fontface  = 'bold', size = 22)  
fig10_3   = plot_grid(subtitle, fig_main, ncol = 1, rel_heights = c(0.08,0.92))
```

## Draw Figure

```{r figure10}
figure10  = plot_grid(fig10_1, fig10_2, ncol = 2, rel_widths = c(0.5,0.5))
#title    = ggdraw() + draw_label("Adaptation to Sparsity (Penalized Linear Regression)", fontface = 'bold', size = 22)
legend   <- get_legend(fig_dummy10 +
                         theme_cowplot(font_size = 22) +
                         theme(legend.box.margin = margin(0, 0, 0, 12),
                               legend.key.size = unit(0.8, "cm")))
yaxis    = ggdraw() + draw_label("predictior error (rmse / sigma)", size = 25, angle = 90)
xaxis    = ggdraw() + draw_label("number of nonzero coefficients (s)", size = 25, angle = 0)
temp     = ggplot() + geom_blank()
figure10  = plot_grid(plot_grid(plot_grid(yaxis, plot_grid(figure10, xaxis, plot_grid(fig10_3, temp, ncol = 2), 
                                                           rel_heights = c(0.47,0.03,0.5), ncol = 1),
                                         rel_widths = c(0.03,0.97), nrow = 1),
                               ncol = 1, rel_heights = c(0.05,0.95)),
                     legend, nrow = 1, rel_widths = c(0.9,0.1))
ggsave("figure10_for_paper.pdf", figure10, width = 18, height = 15)
```

