---
title: "figure7_for_the_paper"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(ggplot2); library(cowplot);
## function for color
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
```

## Figure

### Scenario 7-10

```{r fig2_1, fig.height=11, fig.width=15, fig.align = "center"}
res_df   = readRDS("results/scenario7-10_box.RDS")
col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
baseline = mean(res_df$pred[res_df$fit == "Mr.ASH"])
fig_main = ggplot(res_df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.4)) + 
  theme_cowplot(font_size = 20) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none", axis.title.y = element_blank()) +
  geom_hline(yintercept = baseline, color = col[1], linetype = "dashed")
suptitle  = ggdraw() + draw_label("Scenarios 7, 8, 9, 10", fontface  = 'bold', size = 24)  
# subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.9", fontface  = 'bold', size = 14) 
fig2_1    = plot_grid(suptitle, fig_main, ncol = 1, rel_heights = c(0.06, 0.95))
```

### Scenario 6

```{r fig2_2, fig.height=11, fig.width=15, fig.align = "center"}
res_df   = readRDS("results/scenario6_box.RDS")
col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
baseline = mean(res_df$pred[res_df$fit == "Mr.ASH"])
fig_main = ggplot(res_df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.4)) + 
  theme_cowplot(font_size = 20) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none", axis.title.y = element_blank()) +
  geom_hline(yintercept = baseline, color = col[1], linetype = "dashed")
suptitle  = ggdraw() + draw_label("Scenario 6 (Real Genotype Design)", fontface  = 'bold', size = 24)  
# subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.9", fontface  = 'bold', size = 14) 
fig2_2    = plot_grid(suptitle, fig_main, ncol = 1, rel_heights = c(0.06, 0.95))
```

### Scenario 11

```{r fig2_3, fig.height=11, fig.width=15, fig.align = "center"}
res_df   = readRDS("results/scenario11_box.RDS")
col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
baseline = mean(res_df$pred[res_df$fit == "Mr.ASH"])
fig_main = ggplot(res_df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.4)) + 
  theme_cowplot(font_size = 20) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none", axis.title.y = element_blank()) +
  geom_hline(yintercept = baseline, color = col[1], linetype = "dashed")
suptitle  = ggdraw() + draw_label("Scenario 11 (Varying p)", fontface  = 'bold', size = 24)  
# subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.9", fontface  = 'bold', size = 14) 
fig2_3    = plot_grid(suptitle, fig_main, ncol = 1, rel_heights = c(0.06, 0.95))
```

### Scenario 1-5

```{r fig2_4, fig.height=11, fig.width=15, fig.align = "center"}
res_df   = readRDS("results/scenario1-5_box.RDS")
col      = gg_color_hue(13)[1:11]
shape    = c(19,17,24,25,9,3,11,4,5,7,8,10,1)[1:11]
baseline = mean(res_df$pred[res_df$fit == "Mr.ASH"])
fig_main = ggplot(res_df) +
  stat_summary(aes(x = fit, y = pred), fun.y = mean, colour = col, geom = "point", shape = 18, size = 3) + 
  stat_summary(aes(x = fit, y = pred), colour = col, fun.y = mean, geom = "point") + 
  geom_boxplot(alpha = 0.1, aes(x = fit, y = pred, color = fit, fill = fit, lower = quantile(pred, .25), 
                                middle = mean(pred), upper = quantile(pred, .75)), outlier.alpha = 0, fatten = 0.9) +
  scale_alpha_manual(values = 0.1) +
  scale_fill_manual(values = col, guide = "none") +
  scale_color_manual(values = col, guide = "none") +
  labs(x           = "") + coord_cartesian(ylim = c(1,1.4)) + 
  theme_cowplot(font_size = 20) + 
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none", axis.title.y = element_blank()) +
  geom_hline(yintercept = baseline, color = col[1], linetype = "dashed")
suptitle  = ggdraw() + draw_label("Scenarios 1, 2, 3, 4, 5", fontface  = 'bold', size = 24) 
# subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 200, s = 1-200, pve = 0.9", fontface  = 'bold', size = 14) 
fig2_4    = plot_grid(suptitle, fig_main, ncol = 1, rel_heights = c(0.06, 0.95))
```

## Draw Figure

```{r figure7}
figure7  = plot_grid(fig2_4,fig2_2,fig2_1,fig2_3, ncol = 2, rel_widths = c(0.5,0.5))
#title    = ggdraw() + draw_label("Adaptation to Sparsity (Penalized Linear Regression)", fontface = 'bold', size = 24)
yaxis    = ggdraw() + draw_label("relative prediction error (pred / min(pred))", size = 25, angle = 90)
figure7  = plot_grid(yaxis, figure7,
                     nrow = 1, rel_widths = c(0.03,0.97))
ggsave("figure7_for_paper.pdf", figure7, width = 18, height = 15)
```

