---
title: "Figure9_Sourcecode"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Source Code

```{r library, message = FALSE}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(mr.ash.alpha); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
```

## Scenarios

### Scenario 1

Scenario 1 (Low-dimensional setting): $n = \textrm{500}$, $p = \textrm{200}$, $s \in [1,p]$, $\textrm{Design} = \textrm{IndepGauss}$, $\textrm{PVE} = 0.5$ and $\textrm{SignalShape} = \textrm{PointNormal}$.

```{r code1, eval = FALSE}
tdat14        = list()
n            = 500
s            = 20
p_range      = c(200,1000,5000,20000)
method_list  = c("mr.ash.g","mcmc")
method_list2 = rep(method_list, 2)
method_num   = length(method_list2)
iter_num     = 20
pred         = matrix(0, iter_num, method_num); colnames(pred) = method_list2
time         = matrix(0, iter_num, method_num); colnames(time) = method_list2
u            = length(method_list)


for (iter in 1:4) {
  p               = p_range[iter]
  for (i in 1:20) {
    data          = simulate_data(n, p, s = s, seed = i, signal = "normal", pve = 0.5)
    
    fit           = fit.lasso(data$X, data$y, data$X.test, data$y.test, seed = i)
    lasso.path.order = mr.ash.alpha:::path.order(fit$fit$glmnet.fit)
    lasso.beta       = as.vector(coef(fit$fit))[-1]
    lasso.time       = c(fit$t, fit$t2)
    
    fit.method    = get(paste("fit.","mcmc",sep = ""))
    fit           = fit.method(data$X, data$y, data$X.test, data$y.test, seed = i, beta.init = lasso.beta + 0)
    pred[i,2]     = fit$rsse / data$sigma / sqrt(n)
    time[i,2]     = fit$t
    
    fit           = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                                sa2 = c(0, 1 / s), sigma2 = data$sigma^2,
                                update.pi = FALSE, pi = c(1 - s/p, s/p),
                                beta.init = lasso.beta, update.order = NULL)
    pred[i,1]     = fit$rsse / data$sigma / sqrt(n)
    time[i,1]     = fit$t
    
    data          = simulate_data(n, p, s = s, seed = i, signal = "normal", pve = 0.5,
                                  design = "equicorrgauss", rho = 0.95)
    
    fit           = fit.lasso(data$X, data$y, data$X.test, data$y.test, seed = i)
    lasso.path.order = mr.ash.alpha:::path.order(fit$fit$glmnet.fit)
    lasso.beta       = as.vector(coef(fit$fit))[-1]
    lasso.time       = c(fit$t, fit$t2)
    
    fit.method    = get(paste("fit.","mcmc",sep = ""))
    fit           = fit.method(data$X, data$y, data$X.test, data$y.test, seed = i, beta.init = lasso.beta + 0)
    pred[i,4]     = fit$rsse / data$sigma / sqrt(n)
    time[i,4]     = fit$t
    
    fit           = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                                sa2 = c(0, 1 / s), sigma2 = data$sigma^2,
                                update.pi = FALSE, pi = c(1 - s/p, s/p),
                                beta.init = lasso.beta, update.order = NULL)
    pred[i,3]     = fit$rsse / data$sigma / sqrt(n)
    time[i,3]     = fit$t
    
    print(c(pred[i,]))
  }
  tdat14[[iter]] = data.frame(pred = c(pred), time = c(time), fit = rep(method_list2, each = 20))
}
```

## Save the results

```{r remove}
try(system("rm *.dat"))
try(system("rm ../*.dat"))
try(system("rm analysis/*.dat"))
try(system("rm ../analysis/*.dat"))
```

```{r saveresults}
saveRDS(tdat14, "results/scenario14.RDS")
```

## Figure

The figure is not presented in the paper. We only use the table.

```{r, eval = FALSE}
res_df       = readRDS("resuls/scenario14.RDS")
method_list  = c("Mr.ASH.g","MCMC","Mr.ASH.g","MCMC")
rho_list     = c(0,0,0.3,0.3,0.95,0.95)
df           = data.frame()
p_range      = c(200,1000,5000,20000)
for (i in 1:4) {
res_df[[i]]$fit   = rep(method_list, each = 20)
df                = rbind(df, data.frame(pred = c(colMeans(matrix(res_df[[i]]$pred, 20, 4))),
                                         time2 = apply(matrix(res_df[[i]]$time, 20, 4, 2, median),
                                         time = c(colMeans(matrix(res_df[[i]]$time, 20, 4))),
                                         p    = p_range[i],
                                         rho  = factor(rho_list),
                                         fit  = method_list))
}
df$fit = factor(df$fit, levels = method_level)
col   = c("darkblue","dodgerblue","darkgreen","limegreen","gold","orange","salmon","skyblue")[c(1,3,5,7)]
shape = c(19,17,24,25,9,3,11,4,5,7,8,1,2,6)[c(1,3,5,7)]
p1    = ggplot(df) + geom_line(aes(x = p, y = pred, color = fit, linetype = rho)) +
  geom_point(aes(x = p, y = pred, color = fit, shape = fit), size = 2.5) +
  theme_cowplot(font_size = 14) +
  scale_x_continuous(trans = "log10", breaks = c(20,50,200,500,2000,10000)) +
  labs(y = "predictior error (rmse / sigma)", x = "number of coefficients (p)") +
  theme(axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.text.x  = element_text(angle = 45,hjust = 1)) +
  scale_color_manual(values = col) +
  scale_shape_manual(values = shape) +
  scale_y_continuous(trans = "log10")
fig_main = p1
title     = ggdraw() + draw_label("Prediction Error (log-scale)", fontface = 'bold', size = 20) 
subtitle  = ggdraw() + draw_label("Scenario: IndepGauss + PointNormal, n = 500, p = 20-10000, s = 20, pve = 0.5", fontface  = 'bold', size = 18) 
fig1.1    = plot_grid(title,subtitle,fig_main, ncol = 1, rel_heights = c(0.05,0.05,0.95))
```