---
title: "Figure10_Sourcecode"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Source Code

```{r library, message = FALSE}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(mr.ash.alpha); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
```

## Scenarios

### Scenario 3-2

```{r code1, eval = TRUE}
tdat1        = list()
n            = 500
p            = 2000
s_range      = c(1,5,20,100,500,2000)
method_list  = c("varbvs","bayesb","blasso","susie","enet","lasso","ridge","scad2","mcp2","l0learn")
method_list2 = c("mr.ash", method_list, "mr.ash.order", "mr.ash.init")
method_num   = length(method_list2)
iter_num     = 20
pred         = matrix(0, iter_num, method_num); colnames(pred) = method_list2
time         = matrix(0, iter_num, method_num); colnames(time) = method_list2
fdp          = matrix(0, iter_num, method_num); colnames(fdp) = method_list2
pow          = matrix(0, iter_num, method_num); colnames(pow) = method_list2


for (iter in 1:6) {
  s            = s_range[iter]
  for (i in 1:20) {
    data          = simulate_data(n, p, s = s, seed = i, signal = "const", pve = 0.5)
    true_support  = (data$beta != 0)
    
    for (j in 1:length(method_list)) {
      fit.method    = get(paste("fit.",method_list[j],sep = ""))
      suppressWarnings(
        fit          <- fit.method(data$X, data$y, data$X.test, data$y.test, seed = i))
      pred[i,j+1]   = fit$rsse / data$sigma / sqrt(n)
      time[i,j+1]   = fit$t
      if (method_list[j] %in% c("varbvs","bayesb","susie")) {
        discoveries       = (fit$pip > 0.5)
      } else {
        discoveries       = (fit$beta != 0)
      }
      fdp[i,j+1]    = compute_fdp(discoveries, true_support)
      pow[i,j+1]    = compute_pow(discoveries, true_support)
      
      if (method_list[j] == "lasso") {
        lasso.path.order = mr.ash.alpha:::path.order(fit$fit$glmnet.fit)
        lasso.beta       = as.vector(coef(fit$fit))[-1]
        lasso.time       = c(fit$t, fit$t2)
      }
    }
    
    fit         = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                             sa2 = (2^((0:19) / 40) - 1)^2)
    pred[i,1]   = fit$rsse / data$sigma / sqrt(n)
    time[i,1]   = fit$t
    discoveries = (fit$pip > 0.5)
    fdp[i,1]    = compute_fdp(discoveries, true_support)
    pow[i,1]    = compute_pow(discoveries, true_support)
    
    fit         = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                              update.order = lasso.path.order,
                              sa2 = (2^((0:19) / 40) - 1)^2)
    pred[i,j+2] = fit$rsse / data$sigma / sqrt(n)
    time[i,j+2] = fit$t + lasso.time[2]
    discoveries = (fit$pip > 0.5)
    fdp[i,j+2]  = compute_fdp(discoveries, true_support)
    pow[i,j+2]  = compute_pow(discoveries, true_support)
    
    fit         = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                              beta.init = lasso.beta,
                              sa2 = (2^((0:19) / 40) - 1)^2)
    pred[i,j+3] = fit$rsse / data$sigma / sqrt(n)
    time[i,j+3] = fit$t + lasso.time[1]
    discoveries = (fit$pip > 0.5)
    fdp[i,j+3]  = compute_fdp(discoveries, true_support)
    pow[i,j+3]  = compute_pow(discoveries, true_support)
    
    print(c(pred[i,]), digits = 3)
  }
  cat("-------------------------------\n")
  print(c(colMeans(pred)), digits = 3)
  tdat1[[iter]] = data.frame(pred = c(pred), time = c(time), fdp = c(fdp),
                             pow = c(pow), fit = rep(method_list2, each = 20))
}
```

### Scenario 4-2

```{r code2, eval = TRUE}
tdat2        = list()
n            = 500
p            = 2000
s_range      = c(1,5,20,100,500,2000)
method_list  = c("varbvs","bayesb","blasso","susie","enet","lasso","ridge","scad2","mcp2","l0learn")
method_list2 = c("mr.ash", method_list, "mr.ash.order", "mr.ash.init")
method_num   = length(method_list2)
iter_num     = 20
pred         = matrix(0, iter_num, method_num); colnames(pred) = method_list2
time         = matrix(0, iter_num, method_num); colnames(time) = method_list2
fdp          = matrix(0, iter_num, method_num); colnames(fdp) = method_list2
pow          = matrix(0, iter_num, method_num); colnames(pow) = method_list2


for (iter in 1:6) {
  s            = s_range[iter]
  for (i in 1:20) {
    data          = simulate_data(n, p, s = s, seed = i, signal = "normal", pve = 0.99)
    true_support  = (data$beta != 0)
    
    for (j in 1:length(method_list)) {
      fit.method    = get(paste("fit.",method_list[j],sep = ""))
      suppressWarnings(
        fit          <- fit.method(data$X, data$y, data$X.test, data$y.test, seed = i))
      pred[i,j+1]   = fit$rsse / data$sigma / sqrt(n)
      time[i,j+1]   = fit$t
      if (method_list[j] %in% c("varbvs","bayesb","susie")) {
        discoveries       = (fit$pip > 0.5)
      } else {
        discoveries       = (fit$beta != 0)
      }
      fdp[i,j+1]    = compute_fdp(discoveries, true_support)
      pow[i,j+1]    = compute_pow(discoveries, true_support)
      
      if (method_list[j] == "lasso") {
        lasso.path.order = mr.ash.alpha:::path.order(fit$fit$glmnet.fit)
        lasso.beta       = as.vector(coef(fit$fit))[-1]
        lasso.time       = c(fit$t, fit$t2)
      }
    }
    
    fit         = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                             sa2 = (2^((0:19) / 20) - 1)^2)
    pred[i,1]   = fit$rsse / data$sigma / sqrt(n)
    time[i,1]   = fit$t
    discoveries = (fit$pip > 0.5)
    fdp[i,1]    = compute_fdp(discoveries, true_support)
    pow[i,1]    = compute_pow(discoveries, true_support)
    
    fit         = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                              update.order = lasso.path.order,
                              sa2 = (2^((0:19) / 20) - 1)^2)
    pred[i,j+2] = fit$rsse / data$sigma / sqrt(n)
    time[i,j+2] = fit$t + lasso.time[2]
    discoveries = (fit$pip > 0.5)
    fdp[i,j+2]  = compute_fdp(discoveries, true_support)
    pow[i,j+2]  = compute_pow(discoveries, true_support)
    
    fit         = fit.mr.ash2(data$X, data$y, data$X.test, data$y.test, seed = i,
                              beta.init = lasso.beta,
                              sa2 = (2^((0:19) / 20) - 1)^2)
    pred[i,j+3] = fit$rsse / data$sigma / sqrt(n)
    time[i,j+3] = fit$t + lasso.time[1]
    discoveries = (fit$pip > 0.5)
    fdp[i,j+3]  = compute_fdp(discoveries, true_support)
    pow[i,j+3]  = compute_pow(discoveries, true_support)
    
    print(c(pred[i,]), digits = 3)
  }
  cat("-------------------------------\n")
  print(c(colMeans(pred)), digits = 3)
  tdat2[[iter]] = data.frame(pred = c(pred), time = c(time), fdp = c(fdp),
                             pow = c(pow), fit = rep(method_list2, each = 20))
}
```

### Scenario 9-2

```{r code3, eval = TRUE}
tdat3        = list()
n            = 500
p            = 2000
s            = 2000
method_list  = c("varbvs","bayesb","blasso","susie","enet","lasso","ridge","scad2","mcp2","l0learn")
method_list2 = c("mr.ash", method_list, "enet2","lasso2","ridge2")
method_num   = length(method_list2)
iter_num     = 20
pred         = matrix(0, iter_num, method_num); colnames(pred) = method_list2
time         = matrix(0, iter_num, method_num); colnames(time) = method_list2

for (iter in 1:8) {
  df           = c(1,2,4,8)
  signal_shape = c("lap","normal","unif","const")
  for (i in 1:20) {
    
    if (iter <= 4) {
      data          = simulate_data(n, p, s = s, seed = i, signal = "t", df = df[iter], pve = 0.5)
    } else if (iter > 4) {
      data          = simulate_data(n, p, s = s, seed = i, signal = signal_shape[iter - 4], pve = 0.5)
    }
    
    for (j in 1:length(method_list)) {
      fit.method    = get(paste("fit.",method_list[j],sep = ""))
      fit           = fit.method(data$X, data$y, data$X.test, data$y.test, seed = i)
      pred[i,j+1]   = fit$rsse / data$sigma / sqrt(n)
      time[i,j+1]   = fit$t
      
      if (method_list[j] == "lasso") {
        pred[i,method_num - 1] = fit$rsse2 / data$sigma / sqrt(n)
      } else if (method_list[j] == "enet") {
        pred[i,method_num - 2] = fit$rsse2 / data$sigma / sqrt(n)
      } else if (method_list[j] == "ridge") {
        pred[i,method_num - 0] = fit$rsse2 / data$sigma / sqrt(n)
      }
    }
    
    fit         = fit.mr.ash(data$X, data$y, data$X.test, data$y.test, seed = i,
                             sa2 = (2^((0:19) / 20) - 1)^2)
    pred[i,1]   = fit$rsse / data$sigma / sqrt(n)
    time[i,1]   = fit$t
    print(c(pred[i,]), digits = 4)
  }
  tdat3[[iter]] = data.frame(pred = c(pred), time = c(time), fit = rep(method_list2, each = 20))
}
```

## Save the results

```{r remove}
try(system("rm *.dat"))
try(system("rm ../*.dat"))
try(system("rm analysis/*.dat"))
try(system("rm ../analysis/*.dat"))
```

```{r saveresults}
saveRDS(tdat1, "results/scenario3-2.RDS")
saveRDS(tdat2, "results/scenario4-2.RDS")
saveRDS(tdat3, "results/scenario9-2.RDS")
```
