---
title: "Result12_Initialization"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

### PVE

We fix PVE = 0.5.

### Packages / Libraries

A list of packages we have loaded is collapsed. Please click "code" to see the list.

```{r library, message = FALSE}
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(varbvs2); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')
```

## Results 

```{r fig1, fig.height=20, fig.width=15}
sdat = readRDS("results/initialization1.RDS")
sdat$fit = factor(sdat$order, levels = c("null.init + increasing.order",
                                         "scad.init + increasing.order",
                                         "lasso.init + increasing.order",
                                         "lasso.init + lasso.pathorder",
                                         "lasso.init + scad.pathorder",
                                         "lasso.init + univar.absorder"))
                 
sdat$vobj = -sdat$vobj + sdat$vobj[1:20]

p1 = my.box(sdat, "fit", "vobj", values = col) +
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none")
subtitle  = ggdraw() + draw_label("Variational Objective", fontface  = 'bold', size = 18)
p1 = plot_grid(subtitle, p1, ncol = 1, rel_heights = c(0.06,0.95))

p2 = my.box(sdat, "fit", "pred", values = col) +
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  scale_y_continuous(trans = "log10", breaks = c(1,1.1,1.2,1.3)) +
  coord_cartesian(ylim = c(1,1.3))
subtitle  = ggdraw() + draw_label("Prediction Error", fontface  = 'bold', size = 18)
p2 = plot_grid(subtitle, p2, ncol = 1, rel_heights = c(0.06,0.95))

p3 = my.box(sdat, "fit", "time", values = col) +
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  scale_y_continuous(trans = "log10")
subtitle  = ggdraw() + draw_label("Computation Time", fontface  = 'bold', size = 18)
p3 = plot_grid(subtitle, p3, ncol = 1, rel_heights = c(0.06,0.95))

p4 = my.box(sdat, "fit", "numiter", values = col) +
  theme(axis.line    = element_blank(),
        axis.text.x  = element_text(angle = 45,hjust = 1),
        legend.position = "none") +
  scale_y_continuous(trans = "log10")
subtitle  = ggdraw() + draw_label("Number of Iterations", fontface  = 'bold', size = 18)
p4 = plot_grid(subtitle, p4, ncol = 1, rel_heights = c(0.06,0.95))
  
title     = ggdraw() + draw_label("Comparison of Update Orders (log-scale)", fontface = 'bold', size = 20) 
subtitle  = ggdraw() + draw_label("Scenario: EquiCorrGauss + SparseNormal, n = 500, p = 2000, s = 20, pve = 0.5, rho = 0.95", fontface  = 'bold', size = 18) 

fig_main  = plot_grid(p1,p2,p3,p4, nrow = 2, rel_widths = c(0.3,0.3,0.3))
fig       = plot_grid(title,subtitle,fig_main, ncol = 1, rel_heights = c(0.06,0.06,0.95))
fig
```

## Source Code

```{r code, eval = FALSE}
setwd("..")
library(Matrix); library(ggplot2); library(cowplot); library(susieR); library(BGLR);
library(glmnet); library(mr.ash); library(ncvreg); library(L0Learn); library(varbvs);
standardize = FALSE
source('code/method_wrapper.R')
source('code/sim_wrapper.R')

tdat1        = list()
n            = 500
p            = 2000
s            = 20
sa2          = (2^((0:19) / 20) - 1)^2
method_list  = c("null.init + increasing.order","lasso.init + increasing.order",
                 "scad.init + increasing.order",
                 "lasso.init + lasso.pathorder", "lasso.init + scad.pathorder",
                 "lasso.init + univar.absorder")
method_num   = length(method_list)
iter_num     = 20
pred         = matrix(0, iter_num, method_num); colnames(pred) = method_list
time         = matrix(0, iter_num, method_num); colnames(time) = method_list
numiter      = matrix(0, iter_num, method_num); colnames(numiter) = method_list
vobj         = matrix(0, iter_num, method_num); colnames(vobj) = method_list


for (i in 1:iter_num) {
  data          = simulate_data(n, p, s = s, seed = i, signal = "normal", rho = 0.95,
                                design = "equicorrgauss", pve = 0.5)
  X             = data$X
  y             = data$y

  fit1             <- fit.lasso(data$X, data$y, data$X.test, data$y.test, seed = i)
  fit2             <- fit.scad2(data$X, data$y, data$X.test, data$y.test, seed = i)
  lasso.path.order = mr.ash:::path.order(fit1$fit$glmnet.fit)
  lasso.beta       = as.vector(coef(fit1$fit))[-1]
  lasso.time       = c(fit1$t, fit1$t2)
  scad.path.order  = mr.ash:::path.order(fit2$fit$fit)
  scad.beta        = as.vector(coef(fit2$fit))[-1]
  scad.time        = c(fit2$t, fit2$t2)
  
  t.mrash1          = system.time(
  fit.mrash1       <- mr.ash(X = X, y = y, sa2 = sa2,
                             max.iter = 2000,
                             standardize = standardize, beta.init = NULL,
                             tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  t.mrash2          = system.time(
  fit.mrash2       <- mr.ash(X = X, y = y, sa2 = sa2,
                            max.iter = 2000,
                             standardize = standardize, beta.init = lasso.beta,
                             tol = list(epstol = 1e-12, convtol = 1e-8)))
  t.mrash3          = system.time(
  fit.mrash3       <- mr.ash(X = X, y = y, sa2 = sa2,
                             max.iter = 2000,
                             standardize = standardize, beta.init = scad.beta,
                             tol = list(epstol = 1e-12, convtol = 1e-8)))
  t.mrash4          = system.time(
  fit.mrash4       <- mr.ash(X = X, y = y, sa2 = sa2,
                             max.iter = 2000,
                             standardize = standardize, beta.init = lasso.beta,
                             update.order = lasso.path.order,
                             tol = list(epstol = 1e-12, convtol = 1e-8)))
  t.mrash5          = system.time(
  fit.mrash5       <- mr.ash(X = X, y = y, sa2 = sa2,
                             max.iter = 2000,
                             standardize = standardize, beta.init = lasso.beta,
                             update.order = scad.path.order,
                             tol = list(epstol = 1e-12, convtol = 1e-8)))
  t.mrash6          = system.time(
  fit.mrash6       <- mr.ash(X = X, y = y, sa2 = sa2,
                             max.iter = 2000,
                             standardize = standardize, beta.init = lasso.beta,
                             update.order = mr.ash:::univar.order(X, y),
                             tol = list(epstol = 1e-12, convtol = 1e-8)))
 
  for (j in 1:6) {
    fit           = get(paste("fit.mrash",j,sep = ""))
    pred[i,j]     = norm(data$y.test - predict(fit, data$X.test), '2') / sqrt(500) / data$sigma
    numiter[i,j]  = fit$iter
    vobj[i,j]     = fit$varobj[fit$iter]
    time[i,j]     = get(paste("t.mrash",j,sep = ""))[3]
  }
  
  print(c(pred[i,]))
}

tdat1 = data.frame(pred = c(pred), vobj = c(vobj), time = c(time),
                   numiter = c(numiter),
                   order = rep(method_list, each = 20))
```
